name: aurore_school
description: A Flutter application for Aurore School management, providing scheduling, QR scanning, and analytics features.
version: 1.0.1+2

environment:
  sdk:  >=3.8.0 <4.0.0  # Exact version for Flutter 3.29 compatibility
  flutter: ">=3.19.5"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.3.0
  firebase_analytics: ^11.4.5
  google_sign_in: ^6.3.0
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  path_provider: ^2.1.5
  mobile_scanner: ^6.0.10
  qr_flutter: ^4.1.0
  dio: ^5.8.0+1
  http: ^2.0.0
  provider: ^6.1.5
  get_it: ^8.0.3
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  image_picker: ^1.1.2
  email_validator: ^3.0.0
  animations: ^2.0.11
  vibration: ^3.1.3
  vibration_platform_interface: ^0.1.0
  fl_chart: ^0.71.0
  vector_math: 2.1.4  # Changed from ^2.1.4 to exact version
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  async: ^2.13.0
  material_color_utilities: ^0.12.0

dependency_overrides:
  vector_math: 2.1.4  # Force override if needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.0.0
  test: ^1.25.15

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    prefer_final_fields: false
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/aurore_logo.png
    - assets/images/login_logo.png
    - assets/images/aurore_icons/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
