name: aurore_school
description: A Flutter application for Aurore School management, providing scheduling, QR scanning, and analytics features.
version: 1.0.1+2

environment:
 sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_analytics: ^11.3.0
  google_sign_in: ^6.1.1
   flutter_secure_storage: ^9.2.4
  crypto: ^3.0.5
  path_provider: ^2.1.5
  mobile_scanner: ^6.0.10
  qr_flutter: ^4.1.0
  dio: ^5.7.0
  http: ^1.2.2
  provider: ^6.1.5
  get_it: ^8.0.3
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  image_picker: ^1.1.2
  email_validator: ^3.0.0
  animations: ^2.0.8
  vibration: ^2.0.0
  vibration_platform_interface: ^0.0.1
  fl_chart: ^0.71.0
  vector_math: ^2.1.4
  intl: ^0.20.2
  flutter_svg: ^2.0.10
  async: ^2.13.0
  material_color_utilities: ^0.12.0
  vector_math: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  test: ^1.25.8

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    prefer_final_fields: false
    always_use_package_imports: true
    avoid_print: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/aurore_logo.png
    - assets/images/login_logo.png
    - assets/icons/dashboard.png
    - assets/icons/timetable.png
    - assets/icons/attendance_present.png
    - assets/icons/attendance_absent.png
    - assets/icons/grades.png
    - assets/icons/profile.png
    - assets/icons/settings.png
    - assets/icons/logout.png
    - assets/icons/communication.png
    - assets/icons/analytics.png
    - assets/icons/qr_scan.png
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
