name: aurore_frontend
description: A Flutter application for Aurore School management
version: 1.0.1+2

environment:
  sdk: '>=3.5.0 <4.0.0'
  # Removed invalid flutter constraint: flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.15.0
  firebase_analytics: ^10.10.7
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  path_provider: ^2.1.5
  mobile_scanner: ^6.0.10
  qr_flutter: ^4.1.0
  dio: ^5.8.0+1
  http: ^1.0.0
  provider: ^6.1.2
  get_it: ^8.0.3
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  image_picker: ^1.1.2
  email_validator: ^3.0.0
  animations: ^2.0.11
  vibration: ^1.9.0
  vibration_platform_interface: ^0.1.0
  fl_chart: ^0.71.0
  vector_math: 2.1.4
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  async: 2.12.0
  material_color_utilities: ^0.11.1

dependency_overrides:
  vector_math: 2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.0.0
  test: ^1.25.15

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    prefer_final_fields: false
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/aurore_logo.png
    - assets/images/aurore_icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
