name: Build Flutter APK and IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true

      # Verify Flutter setup
      - name: Run flutter doctor
        run: flutter doctor -v

      # Navigate to project directory
      - name: Navigate to project directory
        run: cd aurore_frontend

      # Install Android SDK command-line tools
      - name: Install Android SDK command-line tools
        run: |
          sdkmanager --install "cmdline-tools;latest" --sdk_root=$ANDROID_HOME
          sdkmanager --list --sdk_root=$ANDROID_HOME

      # Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses --sdk_root=$ANDROID_HOME

      # Get Flutter dependencies
      - name: Get dependencies
        run: flutter pub get
        working-directory: aurore_frontend

      # Fix dependency conflicts
      - name: Update pubspec.yaml for dependency conflicts
        run: |
          sed -i '' 's/firebase_auth: ^6.3.0/firebase_auth: ^5.6.0/' pubspec.yaml
          sed -i '' 's/material_color_utilities: ^0.12.0/material_color_utilities: ^0.11.1/' pubspec.yaml
        working-directory: aurore_frontend

      # Run flutter pub get again after dependency fixes
      - name: Get dependencies after fixes
        run: flutter pub get
        working-directory: aurore_frontend

      # Set NDK version (if needed)
      - name: Set NDK version
        run: |
          sed -i '' 's/ndkVersion.*/ndkVersion "27.0.12077973"/' android/app/build.gradle.kts
        working-directory: aurore_frontend

      # Build APK
      - name: Build APK
        run: flutter build apk --release --no-debug
        working-directory: aurore_frontend
        env:
          FLUTTER_BUILD_MODE: release

      # Build IPA
      - name: Build IPA
        run: flutter build ios --release --no-codesign --no-debug
        working-directory: aurore_frontend
        env:
          FLUTTER_BUILD_MODE: release

      # Log build configuration
      - name: Log build details
        run: |
          echo "Build mode: $FLUTTER_BUILD_MODE"
          flutter analyze
        working-directory: aurore_frontend

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: aurore_frontend/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      # Upload IPA artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-release-ipa
          path: aurore_frontend/build/ios/ipa/*.ipa
          retention-days: 7

      # Enable debug logging for troubleshooting
      - name: Enable debug logging
        if: failure()
        run: |
          echo "Flutter build failed. Check logs for details."
          flutter build apk --release --verbose
        working-directory: aurore_frontend
