name: Aurore Frontend APK Builder
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Fix Dependencies
        working-directory: ./aurore_frontend
        run: |
          # Update all dependencies to compatible versions
          sed -i \
            -e 's/sdk: ">=3.8.0 <4.0.0"/sdk: ">=3.4.0 <4.0.0"/' \
            -e 's/firebase_core: .*/firebase_core: ^1.24.0/' \
            -e 's/firebase_auth: .*/firebase_auth: ^3.11.2/' \
            -e 's/http: .*/http: ^0.13.5/' \
            pubspec.yaml

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Configure Environment
        run: |
          flutter config --no-analytics >/dev/null 2>&1
          flutter config --no-cli-animations >/dev/null 2>&1

      - name: Get Dependencies
        working-directory: ./aurore_frontend
        run: flutter pub get

      - name: Build APK
        working-directory: ./aurore_frontend
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=/build \
            --obfuscate

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aurore-app-release
          path: aurore_frontend/build/app/outputs/flutter-apk/app-release.apk
