name: Build APK

on:
  push:
    branches:
      - update-gradle

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.2'
        channel: 'stable'

    - name: Clear Gradle Cache
      run: |
        rm -rf ~/.gradle/caches

    - name: Debug Gradle Wrapper Setup
      run: |
        cd android
        ls -la
        chmod +x gradlew
        ./gradlew --version

    - name: Update Gradle Wrapper
      run: |
        cd android
        chmod +x gradlew
        ./gradlew wrapper --gradle-version 8.9 --distribution-type all

    - name: Verify Gradle Version After Update
      run: |
        cd android
        ./gradlew --version

    - name: Install Android NDK 27.0.12077973
      run: |
        echo "Installing NDK 27.0.12077973..."
        sdkmanager --install "ndk;27.0.12077973"
        echo "NDK installed at $ANDROID_HOME/ndk/27.0.12077973"
      env:
        ANDROID_HOME: $ANDROID_SDK_ROOT

    - name: Remove other NDK versions
      run: |
        echo "Removing other NDK versions..."
        ls -d $ANDROID_HOME/ndk/* | grep -v 27.0.12077973 | xargs rm -rf
      env:
        ANDROID_HOME: $ANDROID_SDK_ROOT

    - name: Debug NDK Setup
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        ls -la $ANDROID_HOME/ndk

    - name: Override minSdkVersion
      run: |
        sed -i 's/minSdkVersion [0-9]*/minSdkVersion 23/' android/app/build.gradle

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK with Gradle Wrapper
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Copy APK to Output
      run: |
        cp android/app/build/outputs/apk/release/app-release.apk build/app/outputs/flutter-apk/app-release.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
