name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.36.0'  # Must use this version for Firebase compatibility
  WORKING_DIR: './aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Exact Flutter Version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.36.0'  # Must be exact version string
          channel: 'stable'
          cache: true

      - name: Verify Installation
        run: |
          flutter --version
          dart --version
          if [[ ! $(flutter --version) == *"3.36.0"* ]]; then
            echo "::error::Wrong Flutter version installed"
            exit 1
          fi

      - name: Prepare Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Set compatible Firebase versions for Flutter 3.36.0
          sed -i \
            -e 's/firebase_core: .*/firebase_core: ^4.3.0/' \
            -e 's/firebase_auth: .*/firebase_auth: ^6.3.0/' \
            -e 's/firebase_analytics: .*/firebase_analytics: ^11.4.5/' \
            -e 's/flutter_svg: .*/flutter_svg: ^2.1.0/' \
            -e 's/http: .*/http: ^1.1.0/' \
            -e 's/material_color_utilities: .*/material_color_utilities: 0.11.1/' \
            pubspec.yaml

          # Ensure SDK constraints match
          sed -i 's/sdk: ">=.*\"/sdk: ">=3.8.0 <4.0.0"/' pubspec.yaml
          sed -i 's/flutter: ">=.*\"/flutter: ">=3.36.0"/' pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter pub get --verbose || {
            echo "::warning::First attempt failed, retrying with clean cache..."
            flutter pub cache repair
            flutter pub get --verbose
          }

      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter clean
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.WORKING_DIR }}/build/app/outputs/flutter-apk/app-release.apk
