name: Aurore Frontend APK Builder
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Fix Pubspec Formatting
        working-directory: ./aurore_frontend
        run: |
          # Fix SDK constraint formatting (add quotes and proper spacing)
          sed -i 's/sdk:  >=3.8.0 <4.0.0/sdk: ">=3.4.0 <4.0.0"/' pubspec.yaml
          
          # Ensure proper YAML formatting
          sed -i 's/^  sdk:/  sdk: /' pubspec.yaml
          
          # Maintain other dependency versions
          sed -i \
            -e 's/firebase_core: .*/firebase_core: ^4.3.0/' \
            -e 's/firebase_auth: .*/firebase_auth: ^6.3.0/' \
            -e 's/http: .*/http: ^2.0.0/' \
            pubspec.yaml

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Build APK
        working-directory: ./aurore_frontend
        run: |
          flutter config --no-analytics
          flutter clean
          flutter pub get
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=/build \
            --obfuscate

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aurore-app-release
          path: aurore_frontend/build/app/outputs/flutter-apk/app-release.apk
