name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  PROJECT_DIR: 'aurore_frontend'  # Confirmed from your screenshots

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{ env.PROJECT_DIR }}  # Checkout directly into the project directory

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: 'flutter-${{ env.FLUTTER_VERSION }}'

      - name: Verify Installation
        run: |
          flutter --version
          flutter doctor -v

      - name: Force Compatible Versions
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Install yq for reliable YAML editing
          sudo snap install yq || sudo apt-get install -y yq

          # Remove all test package references
          yq eval 'del(.dependencies.test)' -i pubspec.yaml
          yq eval 'del(.dev_dependencies.test)' -i pubspec.yaml

          # Set exact compatible versions
          yq eval '.dev_dependencies.flutter_test.sdk = "flutter"' -i pubspec.yaml
          yq eval '.dependencies.firebase_core = "2.24.0"' -i pubspec.yaml
          yq eval '.dependencies.firebase_auth = "4.11.0"' -i pubspec.yaml
          yq eval '.environment.sdk = ">=3.4.0 <4.0.0"' -i pubspec.yaml
          yq eval '.environment.flutter = ">=3.22.0 <4.0.0"' -i pubspec.yaml

          # Verify changes
          echo "Final pubspec.yaml:"
          cat pubspec.yaml | grep -E "flutter_test|firebase|sdk|flutter:"

      - name: Resolve Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Clean environment
          rm -f pubspec.lock
          flutter clean
          
          # Get dependencies with retry
          flutter pub get || (sleep 5 && flutter pub get)

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -e
          flutter build apk --release \
            --no-sound-null-safety \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
