name: Flutter APK Builder (Version-Guaranteed)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: '3.16.9'  # Contains Dart 3.8.6
  FLUTTER_HOME: '/opt/flutter'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter (Verified Version)
        run: |
          # Clean environment
          sudo rm -rf /usr/local/flutter
          sudo rm -rf /opt/hostedtoolcache/flutter
          
          # Download Flutter (without checksum verification)
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz -O flutter.tar.xz
          sudo tar xf flutter.tar.xz -C /opt
          sudo chmod -R a+rw /opt/flutter
          
          # Add to PATH
          echo "/opt/flutter/bin" >> $GITHUB_PATH
          echo "/opt/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      - name: Verify Dart Version
        run: |
          /opt/flutter/bin/flutter --version
          DART_VERSION=$(/opt/flutter/bin/dart --version 2>&1 | awk '{print $4}')
          REQUIRED="3.8.0"
          
          if [ "$(printf '%s\n' "$REQUIRED" "$DART_VERSION" | sort -V | head -n1)" != "$REQUIRED" ]; then
            echo "::error::Dart version $DART_VERSION < required $REQUIRED"
            echo "Contents of Dart SDK directory:"
            ls -la /opt/flutter/bin/cache/dart-sdk
            exit 1
          fi

      - name: Setup Android Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | /opt/flutter/bin/sdkmanager --licenses || true
          yes | /opt/flutter/bin/flutter doctor --android-licenses || true

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          /opt/flutter/bin/flutter pub get
          /opt/flutter/bin/flutter build apk --release --shrink

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
