name: Flutter CI/CD with Correct Download URL

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: '3.30.0'  # Contains Dart 3.8.0+
  FLUTTER_HOME: '/home/runner/flutter'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter (Correct URL)
        run: |
          # Clean installation
          rm -rf ${{ env.FLUTTER_HOME }}
          mkdir -p ${{ env.FLUTTER_HOME }}

          # CORRECT download URL format
          FLUTTER_URL="https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz"
          
          # Download with retries and progress
          echo "Downloading Flutter from: $FLUTTER_URL"
          curl -L --retry 3 --progress-bar "$FLUTTER_URL" -o flutter.tar.xz
          
          # Verify download size (minimum 700MB expected)
          FILE_SIZE=$(stat -c%s flutter.tar.xz)
          if [ "$FILE_SIZE" -lt 700000000 ]; then
            echo "::error::Downloaded file is too small ($FILE_SIZE bytes), likely corrupted"
            exit 1
          fi
          
          # Extract with validation
          echo "Extracting Flutter..."
          tar -xJf flutter.tar.xz -C ${{ env.FLUTTER_HOME }} --strip-components=1
          echo "${{ env.FLUTTER_HOME }}/bin" >> $GITHUB_PATH

      - name: Verify Installation
        run: |
          flutter --version
          dart --version
          
          # Verify Dart version meets requirements
          DART_VERSION=$(dart --version 2>&1 | awk '{print $4}')
          REQUIRED="3.8.0"
          if [ "$(printf '%s\n' "$REQUIRED" "$DART_VERSION" | sort -V | head -n1)" != "$REQUIRED" ]; then
            echo "::error::Dart version $DART_VERSION < required $REQUIRED"
            exit 1
          fi

      - name: Setup Android Licenses
        run: |
          mkdir -p ~/.android
          echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.android/licenses.properties

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get
          flutter build apk --release --no-sound-null-safety --shrink

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
