name: Flutter APK Builder (GHCR)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  # Using GitHub Container Registry image
  FLUTTER_VERSION: '3.19.5'
  DOCKER_IMAGE: 'ghcr.io/cirruslabs/flutter:${{ env.FLUTTER_VERSION }}'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Flutter image
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}
          docker run --rm ${{ env.DOCKER_IMAGE }} flutter --version
          docker run --rm ${{ env.DOCKER_IMAGE }} dart --version

      - name: Build APK in Docker
        run: |
          docker run \
            --rm \
            --volume=${{ github.workspace }}:/app \
            --workdir=/app/${{ env.PROJECT_DIR }} \
            -e FLUTTER_PUB_CACHE=/app/.pub-cache \
            ${{ env.DOCKER_IMAGE }} \
            /bin/bash -c "
            flutter config --no-analytics && \
            flutter pub get && \
            flutter build apk --release --shrink && \
            chmod -R a+rw /app/${{ env.PROJECT_DIR }}/build
            "

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
