name: Flutter APK Builder (Self-Contained)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: '3.19.5'  # Contains Dart 3.9.5
  FLUTTER_HOME: '/opt/flutter'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Complete Flutter Bundle
        run: |
          # Clean environment
          sudo rm -rf /usr/local/flutter
          sudo rm -rf /opt/hostedtoolcache/flutter
          
          # Download complete Flutter bundle with SDKs included
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz
          sudo tar xf flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz -C /opt
          sudo chmod -R a+rw /opt/flutter
          
          # Disable any SDK updates
          echo "disable-dart-sdk-update=true" | sudo tee /opt/flutter/bin/internal/engine.version
          echo "disable-flutter-sdk-update=true" | sudo tee -a /opt/flutter/bin/internal/engine.version
          
          # Add to PATH
          echo "/opt/flutter/bin" >> $GITHUB_PATH

      - name: Verify Installation
        run: |
          # Force use of bundled SDKs
          export FLUTTER_STORAGE_BASE_URL="file:///opt/flutter"
          export PUB_HOSTED_URL="file:///opt/flutter"
          
          /opt/flutter/bin/flutter --version --verify-version
          /opt/flutter/bin/dart --version
          
          # Strict version check
          DART_VERSION=$(/opt/flutter/bin/dart --version 2>&1 | awk '{print $4}')
          REQUIRED="3.8.0"
          if [ "$(printf '%s\n' "$REQUIRED" "$DART_VERSION" | sort -V | head -n1)" != "$REQUIRED" ]; then
            echo "::error::Dart version $DART_VERSION < required $REQUIRED"
            echo "Contents of /opt/flutter/bin/cache/dart-sdk:"
            ls -la /opt/flutter/bin/cache/dart-sdk
            exit 1
          fi

      - name: Setup Android Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | /opt/flutter/bin/sdkmanager --licenses
          yes | /opt/flutter/bin/flutter doctor --android-licenses

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          /opt/flutter/bin/flutter pub get
          /opt/flutter/bin/flutter build apk --release --shrink

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
