name: Aurore Frontend APK Builder
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Update SDK Constraints
        working-directory: ./aurore_frontend
        run: |
          # Update SDK constraints to match available Dart version (3.7.0)
          sed -i 's/sdk: ">=3.8.0 <4.0.0"/sdk: ">=3.7.0 <4.0.0"/' pubspec.yaml
          
          # Update other dependencies to versions compatible with Dart 3.7.0
          sed -i \
            -e 's/http: .*/http: ^0.13.5/' \
            -e 's/test: .*/test: ^1.24.3/' \
            pubspec.yaml

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Build APK
        working-directory: ./aurore_frontend
        run: |
          flutter config --no-analytics >/dev/null 2>&1
          flutter clean
          flutter pub get
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=/build \
            --obfuscate

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aurore-app-release
          path: aurore_frontend/build/app/outputs/flutter-apk/app-release.apk
