name: Build APK

on:
  push:
    branches:
      - main  # Adjust this to match your default branch, e.g., 'develop' or 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # Changed from 'adopt' (Adoptium is now Eclipse Temurin)

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.2'  # Replace with your project's Flutter version
        channel: 'stable'

    - name: Clear Gradle Cache
      run: |
        rm -rf ~/.gradle/caches

    - name: Download and Set Up Gradle 8.9
      run: |
        wget https://services.gradle.org/distributions/gradle-8.9-bin.zip -P /tmp
        unzip /tmp/gradle-8.9-bin.zip -d /tmp
        echo "GRADLE_HOME=/tmp/gradle-8.9" >> $GITHUB_ENV
        echo "/tmp/gradle-8.9/bin" >> $GITHUB_PATH

    - name: Verify Gradle Version
      run: |
        /tmp/gradle-8.9/bin/gradle --version

    - name: Install Flutter Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v3  # Changed from SHA to version tag
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
