name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.3'  # Known to include Dart 3.8.0+
  PROJECT_DIR: 'aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Correct Flutter Version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Verify Dart Version
        run: |
          # Force correct Dart version
          flutter upgrade --force
          
          echo "=== Version Verification ==="
          flutter --version
          dart --version
          
          # Check Dart version meets requirements
          DART_VERSION=$(dart --version 2>&1 | awk '{print $4}')
          REQUIRED_VERSION="3.8.0"
          
          if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$DART_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
            echo "::error::Incorrect Dart version detected: $DART_VERSION (Required >= $REQUIRED_VERSION)"
            echo "This Flutter version should include Dart 3.8.0+"
            echo "Trying manual Dart SDK installation..."
            
            # Install Dart SDK directly as fallback
            wget https://storage.googleapis.com/dart-archive/channels/stable/release/3.8.0/sdk/dartsdk-linux-x64-release.zip
            unzip dartsdk-linux-x64-release.zip
            export PATH="$PWD/dart-sdk/bin:$PATH"
            
            # Verify again
            NEW_DART_VERSION=$(dart --version 2>&1 | awk '{print $4}')
            if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$NEW_DART_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
              echo "::error::Failed to install correct Dart version"
              exit 1
            fi
            echo "Successfully installed Dart $NEW_DART_VERSION"
          fi

      - name: Resolve Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter build apk --release \
            --no-sound-null-safety \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
