name: Flutter APK Builder (Dart 3.8.6 - Guaranteed)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: '3.16.9'
  FLUTTER_HOME: '/opt/flutter'
  DART_VERSION: '3.8.6'
  DART_SDK_PATH: './tools/dart-sdk/dart-sdk-linux-x64.zip'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get the SDK file

      - name: Verify SDK Exists
        run: |
          echo "Checking for Dart SDK at ${{ env.DART_SDK_PATH }}"
          if [ -f "${{ env.DART_SDK_PATH }}" ]; then
            echo "Dart SDK found - file size: $(du -h ${{ env.DART_SDK_PATH }} | cut -f1)"
          else
            echo "::error::CRITICAL: Dart SDK file missing!"
            echo "You MUST complete these EXACT steps:"
            echo ""
            echo "1. Run these commands in your LOCAL repository:"
            echo "   cd path/to/your/project"
            echo "   mkdir -p tools/dart-sdk"
            echo "   curl -L https://storage.googleapis.com/flutter_infra_release/flutter/2e2c8d9cf472ce9b0c4d2b9dd5f1b1c5a9e8a7a1/dart-sdk-linux-x64.zip -o tools/dart-sdk/dart-sdk-linux-x64.zip"
            echo "   git add tools/dart-sdk/dart-sdk-linux-x64.zip"
            echo "   git commit -m 'Add Dart SDK'"
            echo "   git push"
            echo ""
            echo "2. Verify the file exists on GitHub:"
            echo "   - Go to your repo in browser"
            echo "   - Navigate to tools/dart-sdk/"
            echo "   - Confirm dart-sdk-linux-x64.zip exists"
            exit 1
          fi

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git unzip

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b ${{ env.FLUTTER_VERSION }} --depth 1 ${{ env.FLUTTER_HOME }}
          echo "${{ env.FLUTTER_HOME }}/bin" >> $GITHUB_PATH

      - name: Install Dart SDK
        run: |
          echo "=== Installing Dart SDK ==="
          rm -rf ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk
          unzip -q ${{ env.DART_SDK_PATH }} -d ${{ env.FLUTTER_HOME }}/bin/cache/
          
          # Verify installation
          DART_ACTUAL=$(${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin/dart --version 2>&1 | awk '{print $4}')
          echo "Installed Dart version: $DART_ACTUAL"
          
          if [ "$DART_ACTUAL" != "${{ env.DART_VERSION }}" ]; then
            echo "::error::Wrong Dart version installed!"
            exit 1
          fi

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get
          flutter build apk --release --shrink

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
