name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  PROJECT_DIR: 'aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-v3.22.0

      - name: Validate and Fix pubspec.yaml
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Create backup
          cp pubspec.yaml pubspec.backup.yaml

          # Extract project metadata safely
          PROJECT_NAME=$(grep '^name:' pubspec.yaml | sed 's/^name: *//; s/:/\\:/g')
          PROJECT_VERSION=$(grep '^version:' pubspec.yaml | sed 's/^version: *//; s/:/\\:/g' || echo '1.0.0+1')
          PROJECT_DESCRIPTION=$(grep '^description:' pubspec.yaml | sed 's/^description: *//; s/:/\\:/g' || echo '')

          # Create new perfectly formatted pubspec.yaml
          {
            echo "name: $PROJECT_NAME"
            echo "description: $PROJECT_DESCRIPTION"
            echo "version: $PROJECT_VERSION"
            echo ""
            echo "environment:"
            echo "  sdk: \">=3.4.0 <4.0.0\""
            echo "  flutter: \">=3.22.0 <4.0.0\""
            echo ""
            echo "dependencies:"
            echo "  flutter:"
            echo "    sdk: flutter"
            echo "  firebase_core: ^2.24.0"
            echo "  firebase_auth: ^4.11.0"
            echo "  test: ^1.24.0"
            echo "  material_color_utilities: ^0.8.0"
            echo "  firebase_analytics: ^11.4.5"
            echo "  google_sign_in: ^6.3.0"
            echo "  flutter_secure_storage: ^9.2.4"
            echo "  crypto: ^3.0.6"
            echo "  path_provider: ^2.1.5"
            echo "  mobile_scanner: ^6.0.10"
            echo "  dio: ^5.8.0+1"
            echo "  http: ^1.0.0"
            echo "  provider: ^6.1.5"
            echo "  get_it: ^8.0.3"
            echo "  google_mlkit_text_recognition: ^0.15.0"
            echo "  google_mlkit_commons: ^0.11.0"
            echo "  image_picker: ^1.1.2"
            echo "  email_validator: ^3.0.0"
            echo "  animations: ^2.0.11"
            echo "  vibration: ^3.1.3"
            echo "  vibration_platform_interface: ^0.1.0"
            echo "  fl_chart: ^0.71.0"
            echo "  vector_math: 2.1.4"
            echo "  intl: ^0.20.2"
            echo "  flutter_svg: ^2.1.0"
            echo "  async: 2.12.0"
            echo ""
            echo "dev_dependencies:"
            echo "  flutter_test:"
            echo "    sdk: flutter"
            echo "  flutter_lints: ^5.0.0"
            echo "  lints: ^5.0.0"
            echo "  test: ^1.25.15"
            echo ""
            echo "flutter:"
            echo "  uses-material-design: true"
            echo "  assets:"
            echo "    - assets/images/aurore_logo.png"
            echo "    - assets/images/login_logo.png"
            echo "    - assets/images/aurore_icons/"
            echo "  fonts:"
            echo "    - family: Inter"
            echo "      fonts:"
            echo "        - asset: fonts/Inter-Regular.ttf"
            echo "        - asset: fonts/Inter-Medium.ttf"
            echo "          weight: 500"
            echo "        - asset: fonts/Inter-SemiBold.ttf"
            echo "          weight: 600"
            echo "        - asset: fonts/Inter-Bold.ttf"
            echo "          weight: 700"
          } > pubspec.yaml

          echo "Final pubspec.yaml contents:"
          cat pubspec.yaml

          # Validate YAML syntax
          if ! python3 -c "import yaml; yaml.safe_load(open('pubspec.yaml'))"; then
            echo "::error::Generated pubspec.yaml has syntax errors"
            exit 1
          fi

      - name: Resolve Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter clean
          flutter pub get

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -e
          flutter build apk --release \
            --no-sound-null-safety \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
