name: Aurore Frontend APK Builder
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Flutter with Dart 3.8.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.33.0'  # This version includes Dart 3.8.0
          channel: 'stable'

      - name: Verify Versions
        run: |
          echo "Flutter version:"
          flutter --version
          echo "Dart version:"
          dart --version
          if ! dart --version 2>&1 | grep -q "3.8.0"; then
            echo "::error::Incorrect Dart version installed!"
            exit 1
          fi

      - name: Build APK
        working-directory: ./aurore_frontend
        run: |
          flutter config --no-analytics >/dev/null 2>&1
          flutter clean
          flutter pub get
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=/build \
            --obfuscate

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aurore-app-release
          path: aurore_frontend/build/app/outputs/flutter-apk/app-release.apk
