name: Flutter CI/CD with Direct Installation

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: 'stable'  # Use valid branch name
  FLUTTER_HOME: '/home/runner/flutter'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter
        run: |
          # Clean installation
          rm -rf ${{ env.FLUTTER_HOME }}
          git clone https://github.com/flutter/flutter.git \
            -b ${{ env.FLUTTER_VERSION }} \
            --depth 1 \
            ${{ env.FLUTTER_HOME }}

          # Add to PATH for CURRENT STEP
          echo "${{ env.FLUTTER_HOME }}/bin" >> $GITHUB_PATH
          export PATH="${{ env.FLUTTER_HOME }}/bin:$PATH"

          # Verify installation
          flutter --version
          flutter precache

      - name: Setup Android Licenses
        run: |
          yes | sdkmanager --licenses || true
          yes | flutter doctor --android-licenses

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get
          flutter build apk --release --shrink

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
