name: Flutter APK Builder (No Demo)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: '3.16.0'  # Contains Dart 3.8.0+
  FLUTTER_HOME: '/home/runner/flutter'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter
        run: |
          # Clean install
          rm -rf ${{ env.FLUTTER_HOME }}
          git clone https://github.com/flutter/flutter.git \
            -b ${{ env.FLUTTER_VERSION }} \
            --depth 1 \
            ${{ env.FLUTTER_HOME }}
          
          # Add to PATH
          echo "${{ env.FLUTTER_HOME }}/bin" >> $GITHUB_PATH
          echo "${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      - name: Verify Versions
        run: |
          flutter --version
          dart --version
          flutter doctor

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Get Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub get

      - name: Build Release APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter build apk \
            --release \
            --shrink \
            --no-tree-shake-icons \
            --target-platform android-arm,android-arm64

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5
