name: Flutter Build APK

on:
  push:
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Xmx6144m"
  _JAVA_OPTIONS: "-Xmx4096m"
  FLUTTER_BUILD_ARGS: "--release --verbose --no-shrink"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-licenses: true
          android-sdk-platform: 34
          build-tools-version: '34.0.0'
          cmake-version: '3.22.1'
          ndk-version: '25.2.9519653'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Validate Environment
        run: |
          flutter doctor -v
          java -version
          ./gradlew --version
        shell: bash

      - name: Clean and Reset
        run: |
          flutter clean
          if [ -d "android" ]; then
            rm -rf android
          fi
          flutter create --platforms android --project-name my_app .
        shell: bash

      - name: Configure Gradle
        run: |
          mkdir -p ~/.gradle
          cat <<EOF > ~/.gradle/gradle.properties
          org.gradle.java.home=$JAVA_HOME
          android.jvmargs=-Xmx6144m -XX:MaxPermSize=1024m
          org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
          org.gradle.daemon=false
          org.gradle.parallel=true
          org.gradle.caching=true
          android.enableJetifier=true
          android.useAndroidX=true
          EOF
        shell: bash

      - name: Prepare Dependencies
        run: |
          flutter pub get
          cd android && ./gradlew clean && ./gradlew dependencies --stacktrace --info && cd ..
        shell: bash

      - name: Build APK (with retry)
        run: |
          set -x
          for i in {1..3}; do
            echo "Attempt $i/3"
            flutter build apk $FLUTTER_BUILD_ARGS > build.log 2>&1
            if [ $? -eq 0 ]; then
              echo "Build succeeded on attempt $i"
              cat build.log | grep -i "warning\|error" || echo "No warnings detected"
              exit 0
            fi
            echo "Build failed on attempt $i"
            cat build.log | grep -i "error\|exception\|fail" || echo "No specific errors found"
            sleep 10
          done
          echo "All build attempts failed"
          exit 1
        shell: bash

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build.log
            android/build/reports/
          retention-days: 7

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
