name: Aurore Frontend APK Builder
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Resolve All Dependencies
        working-directory: ./aurore_frontend  # Fix typo: "working-directory"
        run: |
          sed -i 's/sdk: ">=3.8.0 <4.0.0"/sdk: ">=3.7.0 <4.0.0"/' pubspec.yaml
          sed -i \
            -e 's/material_color_utilities: .*/material_color_utilities: 0.11.1/' \
            -e 's/firebase_core: .*/firebase_core: ^1.24.0/' \
            -e 's/firebase_auth: .*/firebase_auth: ^3.11.2/' \
            -e 's/firebase_analytics: .*/firebase_analytics: ^9.3.2/' \
            -e 's/http: .*/http: ^0.13.5/' \
            -e 's/test: .*/test: ^1.24.3/' \
            -e 's/google_sign_in: .*/google_sign_in: ^5.4.0/' \
            pubspec.yaml

          if ! grep -q "dependency_overrides:" pubspec.yaml; then
            echo -e "\ndependency_overrides:" >> pubspec.yaml
          fi
          if ! grep -q "material_color_utilities:" pubspec.yaml; then
            echo "  material_color_utilities: 0.11.1" >> pubspec.yaml
          fi

      - name: Verify Dependencies
        working-directory: ./aurore_frontend  # Fix typo: "working-directory"
        run: |
          echo "Final dependencies:"
          cat pubspec.yaml
          flutter pub get

      - name: Build APK
        working-directory: ./aurore_frontend
        run: |
          flutter config --no-analytics
          flutter clean
          flutter pub get
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=/build \
            --obfuscate

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aurore-app-release
          path: aurore_frontend/build/app/outputs/flutter-apk/app-release.apk  # Remove "aurore_frontend/" prefix
