name: Build APK

on:
  push:
    branches:
      - update-gradle
  pull_request:
    branches:
      - update-gradle

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with a specific path
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: aurore-FRONTEND

      # Set up Java (required for Android builds)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # Latest stable version as of May 2025
          channel: 'stable'

      # Verify working directory
      - name: Verify directory
        run: |
          pwd
          ls -la .
          ls -la ./aurore_frontend || { echo "Error: aurore_frontend directory not found"; exit 1; }
          ls -la ./aurore_frontend/pubspec.yaml || { echo "Error: pubspec.yaml not found in aurore_frontend"; exit 1; }

      # Get Flutter dependencies
      - name: Install dependencies
        working-directory: ./aurore_frontend
        run: flutter pub get

      # Build the APK
      - name: Build APK
        working-directory: ./aurore_frontend
        run: |
          flutter build apk --release
          ls -la build/app/outputs/flutter-apk/ || { echo "Error: APK build failed or output not found"; exit 1; }

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: aurore-FRONTEND/aurore_frontend/build/app/outputs/flutter-apk/app-release.apk
