name: Flutter APK Builder (Docker-Enforced)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: '3.19.5'  # Contains Dart 3.9.5

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Verify Docker Image
        run: |
          docker pull ghcr.io/cirruslabs/flutter:${{ env.FLUTTER_VERSION }}
          docker run --rm ghcr.io/cirruslabs/flutter:${{ env.FLUTTER_VERSION }} flutter --version
          docker run --rm ghcr.io/cirruslabs/flutter:${{ env.FLUTTER_VERSION }} dart --version

      - name: Build APK in Docker
        run: |
          docker run \
            --rm \
            --volume=${{ github.workspace }}:/app \
            --workdir=/app/${{ env.PROJECT_DIR }} \
            ghcr.io/cirruslabs/flutter:${{ env.FLUTTER_VERSION }} \
            /bin/bash -c "
            flutter pub get &&
            flutter build apk --release --shrink &&
            chmod -R a+rw /app/${{ env.PROJECT_DIR }}/build
            "

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
