name: Flutter Build APK

on:
  push:
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Xmx6144m"
  _JAVA_OPTIONS: "-Xmx6144m -XX:MaxMetaspaceSize=2048m -XX:+HeapDumpOnOutOfMemoryError"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-licenses: true
          android-sdk-platform: 34
          build-tools-version: '34.0.0'
          cmake-version: '3.22.1'
          ndk-version: '25.2.9519653'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Nuclear Clean
        run: |
          # Obliterate all caches and build artifacts
          flutter clean
          rm -rf android/.gradle android/build build
          # Avoid removing ~/.gradle/caches to respect GitHub Actions caching
        shell: bash

      - name: Regenerate Project
        run: |
          # Create fresh Android project
          flutter create --platforms android --project-name app .
          
          # Critical configuration files
          mkdir -p ~/.gradle
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "flutter.sdk=$FLUTTER_ROOT" >> android/local.properties
          
          # Nuclear Gradle wrapper generation
          cd android && gradle wrapper --gradle-version 8.0.2 --distribution-type=bin && cd ..
          chmod +x android/gradlew
          
          # Ultimate Gradle configuration
          cat <<EOF > ~/.gradle/gradle.properties
          org.gradle.java.home=$JAVA_HOME
          android.jvmargs=-Xmx6144m
          org.gradle.jvmargs=-Xmx6144m -XX:+HeapDumpOnOutOfMemoryError
          org.gradle.daemon=false
          org.gradle.parallel=false
          org.gradle.caching=false
          org.gradle.configureondemand=false
          android.enableJetifier=true
          android.useAndroidX=true
          EOF
        shell: bash

      - name: Build with Nuclear Debugging
        run: |
          set -ex
          flutter pub get
          
          # Build with ultimate diagnostics
          cd android && ./gradlew clean assembleRelease \
            --stacktrace \
            --info \
            --no-daemon \
            --no-build-cache \
            --no-configure-on-demand \
            --no-parallel \
            > ../gradle.log 2>&1 || (cat ../gradle.log && exit 1)
          
          # Final verification
          if [ ! -f "../build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "### ULTIMATE BUILD FAILURE ANALYSIS ###"
            echo "### GRADLE DEPENDENCIES ###"
            ./gradlew dependencies
            echo "### BUILD FILES ###"
            find ../build -type f | xargs ls -la
            echo "### ANDROID MANIFEST ###"
            cat app/src/main/AndroidManifest.xml
            exit 1
          fi
        shell: bash

      - name: Upload Nuclear Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: nuclear-debug-data
          path: |
            gradle.log
            android/build/**/*
            ~/.gradle/
            build/
          retention-days: 7

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
