name: Flutter APK Builder (Official Docker)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  # Using official Flutter image with exact version
  DOCKER_IMAGE: 'flutter:3.19.5'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Verify Docker Image Contents
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}
          # Force correct Dart version installation
          docker run --rm ${{ env.DOCKER_IMAGE }} bash -c "
            flutter --version
            dart --version
            if ! dart --version | grep -q 'version 3.9'; then
              echo '::error::Incorrect Dart version in image'
              exit 1
            fi
          "

      - name: Build APK in Docker
        run: |
          docker run \
            --rm \
            --volume=${{ github.workspace }}:/app \
            --workdir=/app/${{ env.PROJECT_DIR }} \
            -e FLUTTER_PUB_CACHE=/app/.pub-cache \
            ${{ env.DOCKER_IMAGE }} \
            /bin/bash -c "
            flutter config --no-analytics && \
            flutter pub get && \
            flutter build apk --release --shrink && \
            chmod -R a+rw /app/${{ env.PROJECT_DIR }}/build
            "

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
