name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  WORKING_DIR: './aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: 'flutter-v3.22.0'

      - name: Verify Installation
        run: |
          flutter --version
          flutter doctor -v

      - name: Force Compatible Dependency Versions
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Create backup
          cp pubspec.yaml pubspec.yaml.bak
          
          # Use Dart for reliable YAML modification
          dart << 'EOF'
          import 'dart:io';

          void main() {
            final file = File('pubspec.yaml');
            var contents = file.readAsStringSync();
            
            // Update test package
            contents = contents.replaceAll(
              RegExp(r'test:\s*[>=^~]*[0-9.]+'),
              'test: ^1.24.0'
            );
            
            // Update other critical dependencies
            contents = contents.replaceAll(
              RegExp(r'flutter_lints:\s*[>=^~]*[0-9.]+'), 
              'flutter_lints: ^2.0.0'
            );
            
            contents = contents.replaceAll(
              RegExp(r'material_color_utilities:\s*[>=^~]*[0-9.]+'),
              'material_color_utilities: ^0.8.0'
            );
            
            // Update SDK constraints
            contents = contents.replaceAll(
              RegExp(r'sdk:\s*"[^"]+"'),
              'sdk: ">=3.4.0 <4.0.0"'
            );
            
            contents = contents.replaceAll(
              RegExp(r'flutter:\s*"[^"]+"'),
              'flutter: ">=3.22.0 <4.0.0"'
            );
            
            file.writeAsStringSync(contents);
          }
          EOF
          
          # Verify changes
          echo "Updated pubspec.yaml:"
          diff pubspec.yaml.bak pubspec.yaml || true
          echo "Test package version:"
          grep "test:" pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter pub get --verbose
          flutter pub outdated

      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          set -e
          flutter clean
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.WORKING_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
