name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'  # This Flutter version includes Dart 3.5.0
  PROJECT_DIR: 'aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Fix SDK Constraints
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Update SDK constraints to match Flutter 3.22.0's Dart (3.5.0)
          sed -i 's/sdk: ">=3.4.0 <4.0.0"/sdk: ">=3.5.0 <4.0.0"/' pubspec.yaml
          sed -i 's/flutter: ">=3.22.0 <4.0.0"/flutter: ">=3.22.0 <4.0.0"/' pubspec.yaml
          echo "Updated SDK constraints:"
          grep -A2 "environment:" pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter build apk --release \
            --no-sound-null-safety \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
