name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  WORKING_DIR: './aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: 'flutter-v3.22.0'

      - name: Verify Installation
        run: |
          flutter --version
          flutter doctor -v

      - name: Update All Dependencies for Compatibility
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Update all version constraints to be compatible with Flutter 3.22.0 (Dart 3.4.0)
          sed -i \
            -e 's/flutter: ">=3.36.0"/flutter: ">=3.22.0 <4.0.0"/' \
            -e 's/sdk: ">=3.8.0 <4.0.0"/sdk: ">=3.4.0 <4.0.0"/' \
            -e 's/test: >=1.25.9/test: ^1.24.7/' \
            -e 's/flutter_lints: ^[0-9.]*/flutter_lints: ^2.0.0/' \
            -e 's/material_color_utilities: ^[0-9.]*/material_color_utilities: ^0.8.0/' \
            -e 's/firebase_core: ^[0-9.]*/firebase_core: ^2.24.0/' \
            -e 's/firebase_auth: ^[0-9.]*/firebase_auth: ^4.11.0/' \
            pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter pub get
          flutter pub outdated

      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          set -e
          flutter clean
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.WORKING_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
