name: Flutter APK Builder (Dart 3.8.0+)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: '3.19.5'  # Contains Dart 3.9.5
  FLUTTER_HOME: '/home/runner/flutter'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Specific Flutter Version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Verify Dart Version
        run: |
          dart --version
          DART_VERSION=$(dart --version 2>&1 | awk '{print $4}')
          REQUIRED="3.8.0"
          if [ "$(printf '%s\n' "$REQUIRED" "$DART_VERSION" | sort -V | head -n1)" != "$REQUIRED" ]; then
            echo "::error::Dart version $DART_VERSION < required $REQUIRED"
            echo "Recommended Flutter versions for Dart 3.8.0+: 3.16.0+"
            exit 1
          fi

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Get Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get

      - name: Build Release APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter build apk \
            --release \
            --shrink \
            --target-platform android-arm,android-arm64

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
