name: Build APK

on:
  push:
    branches:
      - update-gradle
  pull_request:
    branches:
      - update-gradle

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with a specific path
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: aurore-FRONTEND

      # Set up Java (required for Android builds)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Fetch the latest stable Flutter version
      - name: Fetch latest stable Flutter version
        run: |
          echo "Fetching the latest stable Flutter version..."
          git clone --depth 1 --branch stable https://github.com/flutter/flutter.git flutter_latest
          cd flutter_latest
          ./bin/flutter --version
          flutter_version=$(./bin/flutter --version --machine | grep -oP '"frameworkVersion": "\K[0-9]+\.[0-9]+\.[0-9]+')
          echo "Latest stable Flutter version: $flutter_version"
          echo "FLUTTER_VERSION=$flutter_version" >> $GITHUB_ENV
          cd ..
          rm -rf flutter_latest

      # Set up Flutter with the latest stable version
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          architecture: 'x64'

      # Verify Flutter and Dart version
      - name: Verify Flutter setup
        run: |
          flutter doctor -v || { echo "Error: Flutter setup failed"; exit 1; }
          flutter --version || { echo "Error: Flutter not found"; exit 1; }
          dart --version || { echo "Error: Dart not found"; exit 1; }
          dart_version=$(dart --version 2>&1 | grep -oP '\d+\.\d+\.\d+')
          echo "Dart version: $dart_version"

      # Accept Android licenses
      - name: Accept Android licenses
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          yes | flutter doctor --android-licenses || { echo "Error: Failed to accept Android licenses"; exit 1; }

      # Verify working directory and project root
      - name: Verify directory
        run: |
          pwd
          ls -la .
          if [ -d "./aurore-FRONTEND" ]; then
            echo "Found aurore-FRONTEND directory"
            cd ./aurore-FRONTEND
            ls -la .
            if [ -d "./aurore_frontend" ]; then
              echo "Found aurore_frontend directory"
              cd ./aurore_frontend
              ls -la .
              if [ -f "pubspec.yaml" ]; then
                echo "Found pubspec.yaml in aurore_frontend"
              else
                echo "Error: pubspec.yaml not found in aurore_frontend"; exit 1
              fi
            else
              echo "Error: aurore_frontend directory not found"; exit 1
            fi
          else
            echo "Error: aurore-FRONTEND directory not found"; exit 1
          fi

      # Get Flutter dependencies (initial run to ensure compatibility)
      - name: Install initial dependencies
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          flutter pub get || { echo "Error: Failed to get initial dependencies"; echo "pubspec.yaml content:"; cat pubspec.yaml; exit 1; }

      # Regenerate Android project structure
      - name: Regenerate Android project
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          # Backup original pubspec.yaml
          cp pubspec.yaml pubspec.yaml.original
          echo "Backed up original pubspec.yaml to pubspec.yaml.original"
          # Backup existing android directory
          if [ -d "android" ]; then
            mv android android_backup
            echo "Backed up existing android directory to android_backup"
          fi
          # Backup lib, assets, and fonts directories
          if [ -d "lib" ]; then
            cp -r lib lib_backup
            echo "Backed up lib directory to lib_backup"
          fi
          if [ -d "assets" ]; then
            cp -r assets assets_backup
            echo "Backed up assets directory to assets_backup"
          fi
          if [ -d "fonts" ]; then
            cp -r fonts fonts_backup
            echo "Backed up fonts directory to fonts_backup"
          fi
          # Create new project structure
          flutter create -t app . --platforms android
          # Restore pubspec.yaml
          mv pubspec.yaml pubspec.yaml.new
          mv pubspec.yaml.original pubspec.yaml
          echo "Restored original pubspec.yaml"
          # Restore lib directory (Dart code)
          if [ -d "lib_backup" ]; then
            rm -rf lib
            mv lib_backup lib
            echo "Restored lib directory"
          else
            echo "Error: lib_backup directory not found"; exit 1
          fi
          # Restore assets
          if [ -d "assets_backup" ]; then
            rm -rf assets
            mv assets_backup assets
            echo "Restored assets directory"
          else
            echo "Warning: assets_backup directory not found, using default"
          fi
          # Restore fonts (if any)
          if [ -d "fonts_backup" ]; then
            rm -rf fonts
            mv fonts_backup fonts
            echo "Restored fonts directory"
          else
            echo "Warning: fonts_backup directory not found, using default"
          fi

      # Fix imports in main.dart to use relative paths
      - name: Update imports in main.dart
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          if [ -f "lib/main.dart" ]; then
            sed -i 's|package:aurore_school/core/constants/app_colors.dart|core/constants/app_colors.dart|' lib/main.dart
            sed -i 's|package:aurore_school/core/providers/auth_provider.dart|core/providers/auth_provider.dart|' lib/main.dart
            sed -i 's|package:aurore_school/core/providers/qr_provider.dart|core/providers/qr_provider.dart|' lib/main.dart
            sed -i 's|package:aurore_school/core/providers/api_service.dart|core/providers/api_service.dart|' lib/main.dart
            sed -i 's|package:aurore_school/core/providers/timetable_controller.dart|core/providers/timetable_controller.dart|' lib/main.dart
            sed -i 's|package:aurore_school/core/providers/ai_detector_provider.dart|core/providers/ai_detector_provider.dart|' lib/main.dart
            sed -i 's|package:aurore_school/features/auth/login_screen.dart|features/auth/login_screen.dart|' lib/main.dart
            sed -i 's|package:aurore_school/features/auth/reset_password_screen.dart|features/auth/reset_password_screen.dart|' lib/main.dart
            sed -i 's|package:aurore_school/features/auth/sign_up_screen.dart|features/auth/sign_up_screen.dart|' lib/main.dart
            sed -i 's|package:aurore_school/features/dashboard/teacher/teacher_dashboard.dart|features/dashboard/teacher/teacher_dashboard.dart|' lib/main.dart
            sed -i 's|package:aurore_school/features/dashboard/student/student_dashboard.dart|features/dashboard/student/student_dashboard.dart|' lib/main.dart
            sed -i 's|package:aurore_school/features/dashboard/admin/admin_dashboard.dart|features/dashboard/admin/admin_dashboard.dart|' lib/main.dart
            sed -i 's|package:aurore_school/features/dashboard/support/support_screen.dart|features/dashboard/support/support_screen.dart|' lib/main.dart
            sed -i 's|package:aurore_school/features/timetable_screen.dart|features/timetable_screen.dart|' lib/main.dart
            sed -i 's|package:aurore_school/utils/secure_storage.dart|utils/secure_storage.dart|' lib/main.dart
            echo "Updated imports in main.dart to use relative paths"
            cat lib/main.dart
          else
            echo "Error: lib/main.dart not found"; exit 1
          fi

      # Get Flutter dependencies (after migration)
      - name: Install dependencies
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          flutter pub get || { echo "Error: Failed to get dependencies"; echo "pubspec.yaml content:"; cat pubspec.yaml; exit 1; }

      # Set up Android SDK with updated NDK version
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-level: '33'
          ndk-version: '27.0.12077973'  # Updated to match plugin requirements

      # Update NDK version in build.gradle.kts
      - name: Update NDK version in build.gradle.kts
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          sed -i '/android {/a \        ndkVersion = "27.0.12077973"' android/app/build.gradle.kts
          echo "Updated NDK version in android/app/build.gradle.kts"
          cat android/app/build.gradle.kts

      # Build the APK
      - name: Build APK
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          flutter build apk --release || { echo "Error: APK build failed"; cat android/app/build.gradle.kts; exit 1; }

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: aurore-FRONTEND/aurore-FRONTEND/aurore_frontend/build/app/outputs/flutter-apk/app-release.apk
