name: Flutter APK Build Pipeline

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0' # Contains Dart 3.8.0
  WORKING_DIR: './aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        run: |
          FLUTTER_HOME="${{ github.workspace }}/flutter"
          echo "FLUTTER_HOME=${FLUTTER_HOME}" >> $GITHUB_ENV
          
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
          tar xf flutter_linux_${FLUTTER_VERSION}-stable.tar.xz -C "${FLUTTER_HOME}" --strip-components=1
          echo "${FLUTTER_HOME}/bin" >> $GITHUB_PATH

      - name: Verify Installation
        run: |
          flutter --version
          dart --version

      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter pub get
          flutter build apk --release
