name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  WORKING_DIR: './aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter (Latest Stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Upgrade Project Structure
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Backup existing files
          mkdir -p backup
          cp -r android backup/
          cp pubspec.yaml backup/
          
          # Create fresh project structure
          flutter create --platforms android --project-name aurore_frontend .
          
          # Restore original files
          cp backup/pubspec.yaml .
          rm -rf android
          cp -r backup/android .
          rm -rf backup
          
          # Update Gradle versions
          sed -i \
            -e 's/agp:.*/agp:8.3.0/' \
            -e 's/gradle:.*/gradle:8.3/' \
            android/build.gradle
          sed -i \
            -e 's/distributionUrl=.*/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-8.3-bin.zip/' \
            android/gradle/wrapper/gradle-wrapper.properties

      - name: Update Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Set exact versions for all dependencies
          sed -i \
            -e 's/async: .*/async: 2.12.0/' \
            -e 's/flutter_secure_storage: .*/flutter_secure_storage: ^9.0.0/' \
            -e 's/material_color_utilities: .*/material_color_utilities: 0.11.1/' \
            -e 's/vector_math: .*/vector_math: 2.1.4/' \
            -e 's/lints: .*/lints: ^6.0.0/' \
            -e 's/firebase_core: .*/firebase_core: ^4.3.0/' \
            -e 's/firebase_auth: .*/firebase_auth: ^6.3.0/' \
            pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter pub upgrade --major-versions
          flutter pub get

      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter clean
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.WORKING_DIR }}/build/app/outputs/flutter-apk/app-release.apk
