name: Flutter Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-licenses: true
          android-sdk-platform: 34
          build-tools-version: 34.0.0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Configure environment
        run: |
          # For nested project structure
          cd aurore_app || echo "Already in root"
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "flutter.sdk=$FLUTTER_HOME" >> android/local.properties

      - name: Build with diagnostics
        run: |
          cd aurore_app || echo "Already in root"
          set -ex
          flutter clean
          flutter pub get
          
          # Build with debug info
          flutter build apk --release --verbose 2>&1 | tee build.log
          
          # Verify APK
          if [ ! -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "::error::APK not found!"
            echo "Build log tail:"
            tail -n 50 build.log
            echo "Directory contents:"
            ls -la build/app/outputs/flutter-apk/ || ls -la build/
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: aurore_app/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
