name: Flutter Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-licenses: true
          android-sdk-platform: 34
          build-tools-version: 34.0.0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Fix Gradle Java Home
        run: |
          # Remove Windows-style Java home from Gradle properties
          find ~/.gradle -name "gradle.properties" -exec sed -i '/org.gradle.java.home/d' {} \;
          
          # Create fresh Gradle properties with correct Java home
          echo "org.gradle.java.home=$JAVA_HOME" > ~/.gradle/gradle.properties
          echo "android.jvmargs=-Xmx4096m" >> ~/.gradle/gradle.properties

      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
