name: Aurore Frontend APK Builder
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Resolve All Dependencies
        working-directory: ./aurore_frontend
        run: |
          # Update http to version compatible with flutter_svg
          sed -i 's/http: ^0.13.5/http: ^1.0.0/' pubspec.yaml
          
          # Ensure other dependencies are correct
          sed -i \
            -e 's/sdk: ">=3.7.0 <4.0.0"/sdk: ">=3.8.0 <4.0.0"/' \
            -e 's/firebase_core: .*/firebase_core: ^4.3.0/' \
            -e 's/firebase_auth: .*/firebase_auth: ^6.3.0/' \
            -e 's/firebase_analytics: .*/firebase_analytics: ^11.4.5/' \
            -e 's/google_sign_in: .*/google_sign_in: ^6.3.0/' \
            -e 's/test: .*/test: ^1.25.15/' \
            -e 's/material_color_utilities: .*/material_color_utilities: ^0.12.0/' \
            -e 's/async: ^2.13.0/async: 2.12.0/' \
            pubspec.yaml

      - name: Verify Dependencies
        working-directory: ./aurore_frontend
        run: |
          echo "Final dependencies:"
          cat pubspec.yaml
          flutter pub get

      - name: Build APK
        working-directory: ./aurore_frontend
        run: |
          flutter config --no-analytics
          flutter clean
          flutter pub get
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=/build \
            --obfuscate

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aurore-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
