name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'  # Updated to support Dart 3.x
          channel: 'stable'

      - name: Clear Gradle Cache
        run: rm -rf ~/.gradle/caches

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2  # More reliable than manual install
        with:
          gradle-version: 8.9

      - name: Install Flutter Dependencies
        run: |
          flutter pub get
          flutter precache --android

      - name: Build APK
        run: flutter build apk --release --no-pub

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7  # Optional: automatically clean up old artifacts
