name: Flutter Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-licenses: true
          android-sdk-platform: 34
          build-tools-version: 34.0.0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # Updated to match your requirements
          channel: 'stable'
          flutter-cache: true

      - name: Configure environment
        run: |
          cd aurore_app || echo "Already in root"
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "flutter.sdk=$FLUTTER_HOME" >> android/local.properties
          echo "flutter.versionCode=1" >> android/local.properties
          echo "flutter.versionName=1.0.0" >> android/local.properties

      - name: Verify Flutter version
        run: |
          cd aurore_app || echo "Already in root"
          flutter --version
          dart --version

      - name: Install dependencies
        run: |
          cd aurore_app || echo "Already in root"
          flutter pub get

      - name: Build APK
        run: |
          cd aurore_app || echo "Already in root"
          flutter clean
          flutter build apk --release --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: aurore_app/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
          if-no-files-found: error
