name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  WORKING_DIR: './aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: 'flutter-v3.22.0'

      - name: Verify Installation
        run: |
          flutter --version
          flutter doctor -v

      - name: Configure Environment
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Adjust constraints to match Flutter 3.22.0 (Dart 3.4.0)
          sed -i \
            -e 's/sdk: ">=3.8.0 <4.0.0"/sdk: ">=3.4.0 <4.0.0"/' \
            -e 's/test: >=1.25.9/test: ^1.24.7/' \
            -e 's/firebase_auth: ^6.3.0/firebase_auth: ^4.11.0/' \
            -e 's/flutter: ">=3.36.0"/flutter: ">=3.22.0"/' \
            pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Run pub cache repair only if needed (saves time)
          flutter pub cache repair > pub_cache.log 2>&1 || echo "Pub cache repair completed (exit code $?)"
          
          # Get dependencies with minimal output
          flutter pub get > pub_get.log 2>&1 || {
            echo "::error::Pub get failed. Last 50 lines:"
            tail -n 50 pub_get.log
            exit 1
          }
          
          flutter pub outdated --mode=null-safety

      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          set -e
          flutter clean
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate > build.log 2>&1 || {
              echo "::error::Build failed. Last 100 lines:"
              tail -n 100 build.log
              exit 1
            }

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.WORKING_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            ${{ env.WORKING_DIR }}/build.log
            ${{ env.WORKING_DIR }}/pub_cache.log
            ${{ env.WORKING_DIR }}/pub_get.log
          retention-days: 30
