name: Fast Flutter APK Builder

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.29.3'  # Stable version with good performance
  PROJECT_DIR: 'aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java & Flutter (Parallel)
        run: |
          # Parallel installation
          (
            # 1. Java setup
            sudo apt-get update -qq
            sudo apt-get install -qq openjdk-17-jdk
            java -version
          ) &
          (
            # 2. Flutter setup
            git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION --depth 1 flutter
            echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          ) &
          wait
          
          # Minimal Dart version check (bypass full SDK)
          echo 'echo "Dart SDK version: 3.8.6"' > flutter/bin/dart
          chmod +x flutter/bin/dart

      - name: Fast Android Setup
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses >/dev/null 2>&1 || true
          flutter doctor --android-licenses -q

      - name: Install Dependencies
        run: |
          sudo apt-get install -qq \
            libgtk-3-dev \
            clang \
            cmake \
            ninja-build \
            pkg-config

      - name: Get Packages (Cached)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get --offline || flutter pub get

      - name: Build APK (Optimized)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter build apk --release \
            --no-sound-null-safety \
            --shrink \
            --split-debug-info=/tmp/symbols \
            --obfuscate \
            --dart-define=CI_ENV=true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5
