name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.30.0'  # Latest stable with Dart 3.8.0+
  PROJECT_DIR: 'aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Latest Compatible Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Force Version Check
        run: |
          # Clean any cached versions
          flutter upgrade --force
          
          echo "=== Version Verification ==="
          flutter --version
          dart --version
          
          # Get exact Dart version
          DART_VERSION=$(dart --version 2>&1 | awk '{print $4}')
          REQUIRED_VERSION="3.8.0"
          
          if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$DART_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
            echo "::error::Dart version $DART_VERSION is too old. Required >= $REQUIRED_VERSION"
            echo "Attempting to install latest stable Flutter..."
            
            # Install latest stable Flutter
            flutter channel stable
            flutter upgrade --force
            
            # Verify again
            NEW_DART_VERSION=$(dart --version 2>&1 | awk '{print $4}')
            if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$NEW_DART_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
              echo "::error::Failed to get required Dart version"
              echo "Current Flutter version: $(flutter --version)"
              exit 1
            fi
            echo "Successfully installed Dart $NEW_DART_VERSION"
          fi

      - name: Accept Android Licenses
        run: |
          yes | sdkmanager --licenses || true
          flutter doctor --android-licenses --verbose

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev

      - name: Resolve Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter build apk --release \
            --no-sound-null-safety \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
