name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'  # Comes with Dart 3.4.0
  PROJECT_DIR: 'aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Force Compatible SDK Version
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Install Python for YAML processing
          sudo apt-get update && sudo apt-get install -y python3 python3-pip
          pip3 install pyyaml

          # Process pubspec.yaml with proper error handling
          python3 << 'EOF'
          import yaml
          import os

          # Read original pubspec.yaml
          with open('pubspec.yaml', 'r') as f:
              original = yaml.safe_load(f)

          # Create new configuration with compatible versions
          new_spec = {
              'name': original.get('name', 'aurore_frontend'),
              'description': original.get('description', ''),
              'version': original.get('version', '1.0.0+1'),
              'environment': {
                  'sdk': ">=3.4.0 <4.0.0",  # Matches Flutter 3.22.0
                  'flutter': ">=3.22.0 <4.0.0"
              },
              'dependencies': original.get('dependencies', {}),
              'dev_dependencies': original.get('dev_dependencies', {})
          }

          # Force compatible Firebase versions
          new_spec['dependencies']['firebase_core'] = '2.24.0'
          new_spec['dependencies']['firebase_auth'] = '4.11.0'
          
          # Ensure material_color_utilities is compatible
          if 'material_color_utilities' in new_spec['dependencies']:
              new_spec['dependencies']['material_color_utilities'] = '0.8.0'

          # Write new pubspec.yaml
          with open('pubspec.yaml', 'w') as f:
              yaml.dump(new_spec, f, sort_keys=False, default_flow_style=False)
          EOF

          echo "Modified pubspec.yaml:"
          cat pubspec.yaml | grep -E "sdk:|flutter:|firebase|material_color_utilities"

      - name: Resolve Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter clean
          flutter pub get

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -e
          flutter build apk --release \
            --no-sound-null-safety \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
