name: Build APK

on:
  push:
    branches:
      - update-gradle
  pull_request:
    branches:
      - update-gradle

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Using Flutter 3.16.9 (newer but still stable with Firebase)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
          architecture: 'x64'

      - name: Verify setup
        run: |
          flutter doctor -v
          flutter --version

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Navigate to project
        run: cd aurore_frontend && ls -la

      # Modern Firebase alternative configuration
      - name: Update Firebase dependencies
        working-directory: ./aurore_frontend
        run: |
          # Backup original files
          cp pubspec.yaml pubspec.yaml.bak
          cp pubspec.lock pubspec.lock.bak 2>/dev/null || true

          # Update to modern Firebase packages
          sed -i 's/firebase_auth: ^5.6.0/firebase_auth: ^6.3.0/' pubspec.yaml
          sed -i 's/firebase_core: .*/firebase_core: ^2.24.0/' pubspec.yaml
          
          # Add required Firebase plugins
          if ! grep -q "firebase_core" pubspec.yaml; then
            echo "  firebase_core: ^2.24.0" >> pubspec.yaml
          fi
          if ! grep -q "firebase_analytics" pubspec.yaml; then
            echo "  firebase_analytics: ^11.3.0" >> pubspec.yaml
          fi

          # Update SDK constraints
          sed -i 's/sdk: ">=.*<4.0.0"/sdk: ">=3.0.0 <4.0.0"/' pubspec.yaml
          sed -i 's/flutter: ">=.*"/flutter: ">=3.16.0"/' pubspec.yaml

          echo "Updated pubspec.yaml:"
          cat pubspec.yaml

      # Dependency resolution with fallback
      - name: Install dependencies
        working-directory: ./aurore_frontend
        run: |
          flutter pub get --verbose || {
            echo "Primary resolution failed, trying fallback..."
            
            # Fallback to slightly older but stable versions
            sed -i 's/firebase_auth: ^6.3.0/firebase_auth: ^5.0.0/' pubspec.yaml
            sed -i 's/firebase_core: ^2.24.0/firebase_core: ^2.18.0/' pubspec.yaml
            
            flutter pub get --verbose || {
              echo "All resolution attempts failed"
              echo "Restoring original files..."
              cp pubspec.yaml.bak pubspec.yaml
              cp pubspec.lock.bak pubspec.lock 2>/dev/null || true
              exit 1
            }
          }

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-level: '33'
          ndk-version: '25.1.8937393'
          build-tools-version: '33.0.2'

      - name: Build APK
        working-directory: ./aurore_frontend
        run: |
          flutter build apk --release
          ls -la build/app/outputs/flutter-apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: aurore_frontend/build/app/outputs/flutter-apk/app-release.apk
