name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  PROJECT_DIR: 'aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Create Valid pubspec.yaml
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Create backup
          cp pubspec.yaml pubspec.backup.yaml

          # Extract project metadata safely
          PROJECT_NAME=$(grep '^name:' pubspec.yaml | sed 's/^name: *//; s/:/\\:/g')
          PROJECT_VERSION=$(grep '^version:' pubspec.yaml | sed 's/^version: *//; s/:/\\:/g' || echo '1.0.0+1')
          PROJECT_DESCRIPTION=$(grep '^description:' pubspec.yaml | sed 's/^description: *//; s/:/\\:/g' || echo '')

          # Create new pubspec.yaml with proper YAML structure
          {
            echo "name: $PROJECT_NAME"
            echo "description: $PROJECT_DESCRIPTION"
            echo "version: $PROJECT_VERSION"
            echo ""
            echo "environment:"
            echo "  sdk: \">=3.4.0 <4.0.0\""
            echo "  flutter: \">=3.22.0 <4.0.0\""
            echo ""
            echo "dependencies:"
            echo "  flutter:"
            echo "    sdk: flutter"
            echo "  firebase_core: \"2.24.0\""
            echo "  firebase_auth: \"4.11.0\""
            echo "  test: \"1.24.0\""
            echo "  material_color_utilities: \"0.8.0\""
          } > pubspec.yaml

          # Add other non-conflicting dependencies with proper indentation
          grep -A 100 '^dependencies:' pubspec.backup.yaml | \
          grep -vE 'flutter:|firebase_core:|firebase_auth:|test:|material_color_utilities:' | \
          grep -v '^dependencies:' | \
          while read -r line; do
            # Skip empty lines and comments, maintain indentation
            if [[ -n "$line" && ! "$line" =~ ^[[:space:]]*# ]]; then
              echo "  $line" >> pubspec.yaml
            fi
          done

          # Add dev_dependencies if they exist
          if grep -q '^dev_dependencies:' pubspec.backup.yaml; then
            echo "" >> pubspec.yaml
            echo "dev_dependencies:" >> pubspec.yaml
            grep -A 100 '^dev_dependencies:' pubspec.backup.yaml | \
            grep -v '^dev_dependencies:' | \
            while read -r line; do
              if [[ -n "$line" && ! "$line" =~ ^[[:space:]]*# ]]; then
                echo "  $line" >> pubspec.yaml
              fi
            done
          fi

          # Add flutter configuration if it exists
          if grep -q '^flutter:' pubspec.backup.yaml; then
            echo "" >> pubspec.yaml
            echo "flutter:" >> pubspec.yaml
            grep -A 100 '^flutter:' pubspec.backup.yaml | \
            grep -v '^flutter:' | \
            while read -r line; do
              if [[ -n "$line" && ! "$line" =~ ^[[:space:]]*# ]]; then
                echo "  $line" >> pubspec.yaml
              fi
            done
          fi

          echo "Final pubspec.yaml contents:"
          cat pubspec.yaml

      - name: Validate YAML Structure
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Simple validation that doesn't require Python
          if ! grep -q "name:" pubspec.yaml || ! grep -q "sdk:" pubspec.yaml; then
            echo "::error::pubspec.yaml is missing required fields"
            exit 1
          fi
          echo "YAML structure appears valid"

      - name: Resolve Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter clean
          flutter pub get

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -e
          flutter build apk --release \
            --no-sound-null-safety \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
