name: Flutter APK Build Pipeline

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  WORKING_DIR: './aurore_frontend'
  FLUTTER_HOME: '${{ github.workspace }}/flutter'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        run: |
          # Create Flutter directory first
          mkdir -p "${{ env.FLUTTER_HOME }}"
          
          # Download Flutter
          echo "Downloading Flutter ${{ env.FLUTTER_VERSION }}..."
          wget -q --show-progress --progress=bar:force:noscroll \
            https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz
          
          # Verify and extract
          echo "Extracting to ${{ env.FLUTTER_HOME }}..."
          tar xf flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz \
            -C "${{ env.FLUTTER_HOME }}" \
            --strip-components=1
          
          # Add to PATH
          echo "${{ env.FLUTTER_HOME }}/bin" >> $GITHUB_PATH
          echo "FLUTTER_HOME=${{ env.FLUTTER_HOME }}" >> $GITHUB_ENV

      - name: Verify Installation
        run: |
          echo "Flutter path: ${{ env.FLUTTER_HOME }}"
          ls -la ${{ env.FLUTTER_HOME }}/bin
          flutter --version

      - name: Adjust SDK Constraints
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          sed -i \
            -e 's/sdk: ">=3.8.0 <4.0.0"/sdk: ">=3.4.0 <4.0.0"/' \
            -e 's/flutter: ">=3.36.0"/flutter: ">=3.22.0"/' \
            pubspec.yaml

      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter pub get
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.WORKING_DIR }}/build/app/outputs/flutter-apk/app-release.apk
