name: Flutter Build APK

on:
  push:
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-licenses: true
          android-sdk-platform: 34
          build-tools-version: '34.0.0'
          cmake-version: '3.22.1'
          ndk-version: '25.2.9519653'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Validate Environment
        run: |
          flutter doctor -v
          java -version
          echo "ANDROID_HOME: $ANDROID_HOME"
          ls -la $ANDROID_HOME
        shell: bash

      - name: Clean and Regenerate Android Files
        run: |
          if [ -d "android" ]; then
            rm -rf android
          fi
          flutter create --platforms android --project-name my_app .
          cd android && ./gradlew clean && cd ..
        shell: bash

      - name: Configure Gradle Properties
        run: |
          mkdir -p ~/.gradle
          cat <<EOF > ~/.gradle/gradle.properties
          org.gradle.java.home=$JAVA_HOME
          android.jvmargs=-Xmx6144m -XX:MaxPermSize=1024m
          org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
          org.gradle.daemon=false
          org.gradle.parallel=true
          org.gradle.caching=true
          org.gradle.configureondemand=true
          EOF
        shell: bash

      - name: Setup Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > android/app/my-release-key.jks
          cat <<EOF > android/key.properties
          storeFile=my-release-key.jks
          storePassword=$KEYSTORE_PASSWORD
          keyAlias=$KEY_ALIAS
          keyPassword=$KEY_PASSWORD
          EOF
        shell: bash

      - name: Prepare Dependencies
        run: |
          flutter pub get
          cd android && ./gradlew dependencies && cd ..
        shell: bash

      - name: Build APK with Detailed Logging
        run: |
          set -x
          flutter clean
          flutter build apk --release --verbose > build.log 2>&1 || (cat build.log && exit 1)
          cat build.log | grep -i "error\|exception\|fail" || echo "No errors found in logs"
        shell: bash

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
