name: Build APK

on:
  push:
    branches:
      - update-gradle
  pull_request:
    branches:
      - update-gradle

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java (required for Android builds)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Flutter with a version compatible with firebase_auth 5.6.0
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.13.9'  # Specific version compatible with firebase_auth 5.6.0
          channel: 'stable'
          architecture: 'x64'

      # Verify Flutter setup
      - name: Verify Flutter setup
        run: |
          flutter doctor -v
          flutter --version
          dart --version

      # Accept Android licenses
      - name: Accept Android licenses
        run: |
          yes | flutter doctor --android-licenses

      # Change directory to aurore_frontend
      - name: Navigate to project directory
        run: |
          cd aurore_frontend
          echo "Current directory: $(pwd)"
          ls -la

      # Verify project structure
      - name: Verify project structure
        working-directory: ./aurore_frontend
        run: |
          if [ ! -f "pubspec.yaml" ]; then
            echo "Error: pubspec.yaml not found in aurore_frontend directory"
            exit 1
          fi
          echo "Project structure verified"

      # Update pubspec.yaml if needed
      - name: Update pubspec constraints
        working-directory: ./aurore_frontend
        run: |
          # Backup original pubspec
          cp pubspec.yaml pubspec.yaml.bak

          # Update SDK constraints
          sed -i 's/sdk: ">=3.8.0 <4.0.0"/sdk: ">=2.19.0 <4.0.0"/' pubspec.yaml
          sed -i 's/flutter: ">=3.36.0"/flutter: ">=3.3.0"/' pubspec.yaml
          
          # Ensure firebase_auth version is correct
          sed -i 's/firebase_auth: ^6.3.0/firebase_auth: ^5.6.0/' pubspec.yaml
          
          echo "Updated pubspec.yaml contents:"
          cat pubspec.yaml

      # Get dependencies with retry logic
      - name: Install dependencies
        working-directory: ./aurore_frontend
        run: |
          for i in {1..3}; do
            flutter pub get && break || {
              echo "Attempt $i failed"
              if [ $i -eq 3 ]; then
                echo "All attempts failed, restoring original pubspec.yaml"
                cp pubspec.yaml.bak pubspec.yaml
                exit 1
              fi
              sleep 5
            }
          done

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-level: '33'
          ndk-version: '25.1.8937393'
          build-tools-version: '33.0.2'

      # Build the APK
      - name: Build APK
        working-directory: ./aurore_frontend
        run: |
          flutter build apk --release --no-sound-null-safety
          ls -la build/app/outputs/flutter-apk/

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: aurore_frontend/build/app/outputs/flutter-apk/app-release.apk
