name: Build APK

on:
  push:
    branches:
      - update-gradle
  pull_request:
    branches:
      - update-gradle

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with a specific path
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: aurore-FRONTEND

      # Set up Java (required for Android builds)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # Latest stable version as of May 2025
          channel: 'stable'

      # Verify Flutter environment
      - name: Verify Flutter setup
        run: |
          flutter doctor -v || { echo "Error: Flutter setup failed"; exit 1; }

      # Verify working directory and project root
      - name: Verify directory
        run: |
          pwd
          ls -la .
          if [ -d "./aurore-FRONTEND" ]; then
            echo "Found aurore-FRONTEND directory"
            cd ./aurore-FRONTEND
            ls -la .
            if [ -f "pubspec.yaml" ]; then
              echo "Found pubspec.yaml in aurore-FRONTEND"
            else
              echo "Error: pubspec.yaml not found in aurore-FRONTEND"; exit 1
            fi
          else
            echo "Error: aurore-FRONTEND directory not found"; exit 1
          fi

      # Get Flutter dependencies
      - name: Install dependencies
        working-directory: ./aurore-FRONTEND
        run: |
          flutter pub get || { echo "Error: Failed to get dependencies"; exit 1; }

      # Set up Android SDK (anticipate Android build issues)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-level: '33' # Use a recent SDK level
          ndk-version: '25.1.8937393' # Use a compatible NDK version

      # Build the APK
      - name: Build APK
        working-directory: ./aurore-FRONTEND
        run: |
          flutter build apk --release || { echo "Error: APK build failed"; exit 1; }
          ls -la build/app/outputs/flutter-apk/ || { echo "Error: APK output directory not found"; exit 1; }
          if [ ! -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "Error: app-release.apk not generated"; exit 1
          fi

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: aurore-FRONTEND/aurore-FRONTEND/build/app/outputs/flutter-apk/app-release.apk
