name: Ultra-Fast Flutter APK Builder

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.29.3'  # Latest stable
  PROJECT_DIR: 'aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java (Cached)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter (Cached)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Bypass Android Licenses
        run: |
          mkdir -p ~/.android
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/licenses.properties
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ~/.android/licenses.properties

      - name: Install Essential Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            libgtk-3-dev \
            cmake \
            ninja-build

      - name: Get Packages (Offline First)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get --offline || flutter pub get

      - name: Build APK (Ultra-Fast)
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter build apk --release \
            --no-sound-null-safety \
            --shrink \
            --obfuscate \
            --dart-define=CI_ENV=true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
