name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Configure environment
        run: |
          # Get Flutter SDK path from Flutter installation
          FLUTTER_PATH=$(which flutter | sed 's/\/bin\/flutter$//')
          echo "FLUTTER_HOME=${FLUTTER_PATH}" >> $GITHUB_ENV
          
          # Create local.properties
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "flutter.sdk=${FLUTTER_PATH}" >> android/local.properties
          echo "flutter.versionCode=1" >> android/local.properties
          echo "flutter.versionName=1.0.0" >> android/local.properties

          echo "Flutter SDK path: ${FLUTTER_PATH}"
          ls -la "${FLUTTER_PATH}/packages/flutter_tools/gradle"

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
