name: Flutter APK Builder (Dart 3.8.6 Working Solution)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: '3.16.9'  # This is the correct version for Dart 3.8.6
  FLUTTER_HOME: '/opt/flutter'
  DART_VERSION: '3.8.6'
  ENGINE_VERSION: '2e2c8d9cf472ce9b0c4d2b9dd5f1b1c5a9e8a7a1'  # Engine hash for Dart 3.8.6

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl git unzip xz-utils \
            libglu1-mesa build-essential \
            libstdc++6 clang cmake ninja-build

      - name: Nuclear Clean
        run: |
          sudo rm -rf /usr/local/flutter
          sudo rm -rf /opt/hostedtoolcache/flutter
          sudo rm -rf ${{ env.FLUTTER_HOME }}
          sudo rm -rf ~/.flutter
          sudo rm -rf ~/.dart*

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b ${{ env.FLUTTER_VERSION }} --depth 1 ${{ env.FLUTTER_HOME }}
          echo "${{ env.FLUTTER_HOME }}/bin" >> $GITHUB_PATH

      - name: Force Correct Dart SDK
        run: |
          echo "=== Installing Dart ${{ env.DART_VERSION }} ==="
          
          # Create engine version file
          mkdir -p ${{ env.FLUTTER_HOME }}/bin/internal
          echo "engine.version=${{ env.ENGINE_VERSION }}" > ${{ env.FLUTTER_HOME }}/bin/internal/engine.version
          
          # Download Dart SDK
          DART_SDK_URL="https://storage.googleapis.com/flutter_infra_release/flutter/${{ env.ENGINE_VERSION }}/dart-sdk-linux-x64.zip"
          echo "Downloading from: $DART_SDK_URL"
          
          for i in {1..5}; do
            wget -q "$DART_SDK_URL" -O dart-sdk.zip && break || sleep 10
          done
          
          if [ ! -f dart-sdk.zip ]; then
            echo "::error::Failed to download Dart SDK after 5 attempts"
            exit 1
          fi
          
          # Install
          rm -rf ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk
          unzip -q dart-sdk.zip -d ${{ env.FLUTTER_HOME }}/bin/cache/
          rm dart-sdk.zip
          
          # Verify
          DART_ACTUAL=$(${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin/dart --version 2>&1 | awk '{print $4}')
          echo "Installed Dart version: $DART_ACTUAL"
          
          if [ "$DART_ACTUAL" != "${{ env.DART_VERSION }}" ]; then
            echo "::error::Dart version still incorrect!"
            exit 1
          fi

      - name: Disable Auto-Update
        run: |
          mkdir -p ${{ env.FLUTTER_HOME }}/bin/internal
          echo "#!/bin/sh" > ${{ env.FLUTTER_HOME }}/bin/internal/update_dart_sdk.sh
          echo "echo 'Dart SDK updates disabled'" >> ${{ env.FLUTTER_HOME }}/bin/internal/update_dart_sdk.sh
          chmod +x ${{ env.FLUTTER_HOME }}/bin/internal/update_dart_sdk.sh

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get
          flutter build apk --release --shrink

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
