name: Flutter Build APK

on:
  push:
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Xmx6144m"
  _JAVA_OPTIONS: "-Xmx4096m"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-licenses: true
          android-sdk-platform: 34
          build-tools-version: '34.0.0'
          cmake-version: '3.22.1'
          ndk-version: '25.2.9519653'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Validate Environment
        run: |
          flutter doctor -v
          java -version
          echo "ANDROID_HOME: $ANDROID_HOME"
          ls -la $ANDROID_HOME
        shell: bash

      - name: Recreate Android Project
        run: |
          # Completely reset Android configuration
          rm -rf android
          flutter create --platforms android --project-name app .
          
          # Ensure gradlew exists and is executable
          if [ ! -f "android/gradlew" ]; then
            cd android && gradle wrapper --gradle-version 8.0.2 && cd ..
          fi
          chmod +x android/gradlew
        shell: bash

      - name: Configure Gradle
        run: |
          mkdir -p ~/.gradle
          cat <<EOF > ~/.gradle/gradle.properties
          org.gradle.java.home=$JAVA_HOME
          android.jvmargs=-Xmx6144m -XX:MaxPermSize=1024m
          org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
          org.gradle.daemon=false
          org.gradle.parallel=true
          org.gradle.caching=true
          android.enableJetifier=true
          android.useAndroidX=true
          EOF
        shell: bash

      - name: Build with Full Diagnostics
        run: |
          set -ex
          flutter clean
          flutter pub get
          
          # Run gradle tasks directly for better logging
          cd android && ./gradlew clean assembleRelease --stacktrace --info --scan && cd ..
          
          # Verify APK exists
          if [ ! -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "APK not generated!"
            exit 1
          fi
        shell: bash

      - name: Upload Build Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            android/build/reports/
            ~/.gradle/
          retention-days: 7

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
