name: Flutter APK Builder (Direct Dart SDK)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: '3.16.9'  # Works with Dart 3.8.6
  DART_VERSION: '3.8.6'       # Explicit version
  FLUTTER_HOME: '/opt/flutter'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 50

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter Base
        run: |
          sudo rm -rf /usr/local/flutter
          sudo rm -rf /opt/hostedtoolcache/flutter
          git clone https://github.com/flutter/flutter.git -b ${{ env.FLUTTER_VERSION }} --depth 1 ${{ env.FLUTTER_HOME }}
          echo "${{ env.FLUTTER_HOME }}/bin" >> $GITHUB_PATH

      - name: Install Correct Dart SDK
        run: |
          # Remove existing Dart SDK
          sudo rm -rf ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk
          
          # Download specific Dart version
          wget https://storage.googleapis.com/dart-archive/channels/stable/release/${{ env.DART_VERSION }}/sdk/dartsdk-linux-x64-release.zip
          unzip dartsdk-linux-x64-release.zip -d ${{ env.FLUTTER_HOME }}/bin/cache/
          mv ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk* ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk
          rm dartsdk-linux-x64-release.zip
          
          # Verify installation
          ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin/dart --version
          echo "${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      - name: Verify Versions
        run: |
          echo "Flutter version:"
          ${{ env.FLUTTER_HOME }}/bin/flutter --version
          echo "Dart version:"
          ${{ env.FLUTTER_HOME }}/bin/dart --version
          
          DART_ACTUAL=$(${{ env.FLUTTER_HOME }}/bin/dart --version 2>&1 | awk '{print $4}')
          if [ "$DART_ACTUAL" != "${{ env.DART_VERSION }}" ]; then
            echo "::error::Dart version mismatch! Actual: $DART_ACTUAL, Required: ${{ env.DART_VERSION }}"
            exit 1
          fi

      - name: Setup Android
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | ${{ env.FLUTTER_HOME }}/bin/sdkmanager --licenses || true
          yes | ${{ env.FLUTTER_HOME }}/bin/flutter doctor --android-licenses || true

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          ${{ env.FLUTTER_HOME }}/bin/flutter pub get
          ${{ env.FLUTTER_HOME }}/bin/flutter build apk --release --shrink

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
