name: Flutter APK Builder (Dart 3.8.6 Confirmed)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: '3.16.9'
  FLUTTER_HOME: '/opt/flutter'
  DART_VERSION: '3.8.6'
  LOCAL_DART_SDK: './tools/dart-sdk/dart-sdk-linux-x64.zip'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get the Dart SDK

      - name: Verify SDK Exists
        run: |
          if [ ! -f "${{ env.LOCAL_DART_SDK }}" ]; then
            echo "::error::Missing Dart SDK!"
            echo "Follow these exact steps to fix:"
            echo "1. Run: mkdir -p tools/dart-sdk"
            echo "2. Download: wget https://storage.googleapis.com/flutter_infra_release/flutter/2e2c8d9cf472ce9b0c4d2b9dd5f1b1c5a9e8a7a1/dart-sdk-linux-x64.zip"
            echo "3. Move: mv dart-sdk-linux-x64.zip tools/dart-sdk/"
            echo "4. Commit and push the file"
            exit 1
          fi
          echo "Dart SDK found - proceeding with build"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl git unzip xz-utils \
            libglu1-mesa build-essential

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b ${{ env.FLUTTER_VERSION }} --depth 1 ${{ env.FLUTTER_HOME }}
          echo "${{ env.FLUTTER_HOME }}/bin" >> $GITHUB_PATH

      - name: Install Dart SDK
        run: |
          echo "=== Installing Dart SDK ==="
          unzip -q ${{ env.LOCAL_DART_SDK }} -d ${{ env.FLUTTER_HOME }}/bin/cache/
          
          # Verify installation
          DART_ACTUAL=$(${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin/dart --version 2>&1 | awk '{print $4}')
          echo "Installed Dart version: $DART_ACTUAL"
          
          if [ "$DART_ACTUAL" != "${{ env.DART_VERSION }}" ]; then
            echo "::error::Version mismatch!"
            exit 1
          fi

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get
          flutter build apk --release --shrink

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
