name: Flutter Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for Gradle wrapper

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-licenses: true
          android-sdk-platform: 34
          build-tools-version: 34.0.0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
          flutter-cache: true

      - name: Configure environment
        run: |
          # Set correct Flutter path
          FLUTTER_ROOT=$(dirname $(dirname $(which flutter)))
          echo "FLUTTER_HOME=$FLUTTER_ROOT" >> $GITHUB_ENV
          
          # Create essential config files
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "flutter.sdk=$FLUTTER_ROOT" >> android/local.properties
          echo "flutter.versionCode=1" >> android/local.properties
          echo "flutter.versionName=1.0.0" >> android/local.properties

      - name: Verify environment
        run: |
          flutter doctor -v
          ls -la "$FLUTTER_HOME/packages/flutter_tools/gradle"

      - name: Build APK (with nuclear fallback)
        run: |
          set -ex  # Enable debug mode and exit on error
          
          # First try normal build
          if ! flutter build apk --release --verbose 2>&1 | tee build.log; then
            echo "::warning::Standard build failed, trying nuclear option"
            
            # Nuclear clean
            rm -rf ~/.gradle
            rm -rf android/.gradle
            flutter pub cache repair
            
            # Retry with different configurations
            flutter build apk --release --no-shrink --verbose 2>&1 | tee build.log ||
            flutter build apk --release --no-tree-shake-icons --verbose 2>&1 | tee build.log ||
            {
              echo "::error::All build attempts failed"
              cat build.log
              exit 1
            }
          fi

          # Verify APK exists
          APK_PATH=$(find . -name "app-release.apk" | head -1)
          if [ -z "$APK_PATH" ]; then
            echo "::error::No APK found after successful build!"
            find . -name "*.apk" || echo "No APK files found"
            exit 1
          fi
          
          # Standardize APK location
          mkdir -p build/app/outputs/flutter-apk/
          cp "$APK_PATH" build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
          if-no-files-found: error
