name: Flutter Build APK

on:
  push:
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Xmx6144m"
  _JAVA_OPTIONS: "-Xmx6144m -XX:MaxMetaspaceSize=2048m"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-licenses: true
          android-sdk-platform: 34
          build-tools-version: '34.0.0'
          cmake-version: '3.22.1'
          ndk-version: '25.2.9519653'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Full Environment Reset
        run: |
          # Clean everything
          flutter clean
          rm -rf android
          
          # Regenerate project
          flutter create --platforms android --project-name app .
          
          # Configure environment
          mkdir -p ~/.gradle
          cat <<EOF > ~/.gradle/gradle.properties
          org.gradle.java.home=$JAVA_HOME
          android.jvmargs=-Xmx6144m -XX:MaxPermSize=1024m
          org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=2048m -XX:+HeapDumpOnOutOfMemoryError
          org.gradle.daemon=false
          org.gradle.parallel=false
          android.enableJetifier=true
          android.useAndroidX=true
          EOF
          
          # Create proper local.properties
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "flutter.sdk=$FLUTTER_ROOT" >> android/local.properties
          
          # Verify files
          ls -la android/
          cat android/local.properties
        shell: bash

      - name: Build with Maximum Debugging
        run: |
          set -ex
          flutter pub get
          
          # Build with all debugging enabled
          cd android && ./gradlew clean assembleRelease \
            --stacktrace \
            --info \
            --no-daemon \
            --no-build-cache \
            --no-parallel \
            --scan \
            > ../gradle.log 2>&1 || (cat ../gradle.log && exit 1)
          
          # Verify APK exists
          if [ ! -f "../build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "### BUILD FAILED ###"
            echo "### Listing build directory ###"
            find ../build -type f | xargs ls -la
            echo "### Gradle build reports ###"
            find android/build/reports -type f | xargs cat || echo "No reports found"
            exit 1
          fi
        shell: bash

      - name: Upload Diagnostics
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-diagnostics
          path: |
            gradle.log
            android/build/**/*.log
            android/build/reports/
          retention-days: 7

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
