name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  PROJECT_DIR: 'aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Force Compatible Versions
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Install yq for YAML processing
          sudo apt-get update && sudo apt-get install -y yq

          # Create backup
          cp pubspec.yaml pubspec.yaml.bak

          # Set exact compatible versions
          yq eval '
            .dependencies.firebase_core = "2.24.0" |
            .dependencies.firebase_auth = "4.11.0" |
            .dependencies.material_color_utilities = "0.8.0" |
            .environment.sdk = ">=3.4.0 <4.0.0" |
            .environment.flutter = ">=3.22.0 <4.0.0"
          ' pubspec.yaml > temp.yaml && mv temp.yaml pubspec.yaml

          echo "Updated dependencies:"
          grep -E "firebase|material_color_utilities|sdk|flutter:" pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter clean
          flutter pub get

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -e
          flutter build apk --release \
            --no-sound-null-safety \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
