name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  PROJECT_DIR: 'aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: 'flutter-${{ env.FLUTTER_VERSION }}'

      - name: Verify Installation
        run: |
          flutter --version
          flutter doctor -v

      - name: Standardize Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Install yq for YAML processing
          sudo snap install yq || sudo apt-get install -y yq

          # Create backup
          cp pubspec.yaml pubspec.yaml.bak

          # Force all test package references to use the same version
          yq eval 'del(.dev_dependencies.test)' -i pubspec.yaml
          yq eval '.dependencies.test = "1.24.0"' -i pubspec.yaml
          yq eval '.dev_dependencies.flutter_test.sdk = "flutter"' -i pubspec.yaml

          # Set other critical dependencies
          yq eval '.environment.sdk = ">=3.4.0 <4.0.0"' -i pubspec.yaml
          yq eval '.environment.flutter = ">=3.22.0 <4.0.0"' -i pubspec.yaml

          # Verify changes
          echo "Modified dependencies:"
          grep -E "test:|flutter_test:" pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Remove lockfile to ensure clean resolution
          rm -f pubspec.lock
          
          # Get dependencies with retry logic
          flutter pub get || (echo "First attempt failed, retrying..." && flutter pub get)
          
          # Verify resolution
          flutter pub outdated --mode=null-safety

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -e
          flutter clean
          flutter build apk --release \
            --no-sound-null-safety \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
