name: Aurore School Frontend CI

on:
  push:
    branches:
      - update-gradle
  pull_request:
    branches:
      - update-gradle

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x' # Use a recent stable version
          channel: 'stable'

      # Cache Flutter dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            **/pubspec.lock
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run code analysis to catch asset errors
      - name: Run flutter analyze
        run: flutter analyze > flutter_analyze.log

      # Run tests
      - name: Run tests
        run: flutter test

      # Upload analysis log as artifact for debugging
      - name: Upload analysis log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flutter-analyze-log
          path: flutter_analyze.log

      # Build APK for verification
      - name: Build APK
        run: flutter build apk --release --verbose > flutter_build.log

      # Upload build log as artifact
      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build-log
          path: flutter_build.log
