name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  WORKING_DIR: './aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.36.0'
          channel: 'stable'
          cache: true

      - name: Prepare Environment
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Set exact versions for all critical dependencies
          sed -i \
            -e 's/path_provider: .*/path_provider: 2.0.17/' \
            -e 's/firebase_core: .*/firebase_core: 4.3.0/' \
            -e 's/firebase_auth: .*/firebase_auth: 6.3.0/' \
            -e 's/flutter_svg: .*/flutter_svg: 2.1.0/' \
            -e 's/http: .*/http: 1.1.0/' \
            -e 's/material_color_utilities: .*/material_color_utilities: 0.11.1/' \
            pubspec.yaml

          # Set SDK constraints to match Flutter 3.36.0
          sed -i \
            -e 's/sdk: ">=.*"/sdk: ">=3.8.0 <4.0.0"/' \
            -e 's/flutter: ">=.*"/flutter: ">=3.36.0"/' \
            pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter pub get --verbose || {
            echo "::warning::First attempt failed, running pub upgrade..."
            flutter pub upgrade --major-versions
          }

      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter clean
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.WORKING_DIR }}/build/app/outputs/flutter-apk/app-release.apk
