name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # Minimum version with Dart 3.4.0
          channel: 'stable'

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Generate local.properties
        run: |
          echo "flutter.sdk=$FLUTTER_HOME" > android/local.properties
          echo "flutter.versionCode=1" >> android/local.properties
          echo "flutter.versionName=1.0.0" >> android/local.properties
          echo "flutter.compileSdkVersion=34" >> android/local.properties
          echo "flutter.minSdkVersion=21" >> android/local.properties
          echo "flutter.targetSdkVersion=34" >> android/local.properties
          echo "flutter.ndkVersion=$(find $ANDROID_HOME/ndk -maxdepth 1 -type d | sort -V | tail -n 1 | xargs basename)" >> android/local.properties

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.9
          cache-disabled: false
          cache-read-only: false

      - name: Install Flutter Dependencies
        run: |
          flutter pub get
          flutter precache --android

      - name: Build APK
        run: |
          flutter clean
          flutter build apk --release --no-pub

      - name: Verify APK
        run: |
          if [ ! -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "APK file not found!"
            ls -la build/app/outputs/flutter-apk/
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
          if-no-files-found: error
