name: Flutter Build APK

on:
  push:
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Xmx6144m"
  _JAVA_OPTIONS: "-Xmx6144m -XX:MaxMetaspaceSize=2048m"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-licenses: true
          android-sdk-platform: 34
          build-tools-version: '34.0.0'
          cmake-version: '3.22.1'
          ndk-version: '25.2.9519653'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Nuclear Reset
        run: |
          # Complete cleanup
          flutter clean
          rm -rf android
          rm -rf ~/.gradle/caches
          
          # Regenerate project
          flutter create --platforms android --project-name app .
          
          # Create critical files
          mkdir -p ~/.gradle
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "flutter.sdk=$FLUTTER_ROOT" >> android/local.properties
          
          # Force Gradle wrapper generation
          cd android && gradle wrapper --gradle-version 8.0.2 --distribution-type=bin && cd ..
          chmod +x android/gradlew
          
          # Configure environment
          cat <<EOF > ~/.gradle/gradle.properties
          org.gradle.java.home=$JAVA_HOME
          android.jvmargs=-Xmx6144m
          org.gradle.jvmargs=-Xmx6144m -XX:+HeapDumpOnOutOfMemoryError
          org.gradle.daemon=false
          org.gradle.parallel=false
          android.enableJetifier=true
          android.useAndroidX=true
          EOF
        shell: bash

      - name: Build with Ultimate Debugging
        run: |
          set -ex
          flutter pub get
          
          # Build with maximum diagnostics
          cd android && ./gradlew clean assembleRelease \
            --stacktrace \
            --info \
            --no-daemon \
            --no-build-cache \
            --no-parallel \
            > ../gradle.log 2>&1 || (cat ../gradle.log && exit 1)
          
          # Nuclear verification
          if [ ! -f "../build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "### CRITICAL BUILD FAILURE ###"
            echo "### BUILD DIRECTORY TREE ###"
            find ../build -type d | xargs ls -la
            echo "### GRADLE FILES ###"
            find android -name "*.gradle" -o -name "*.properties" | xargs cat
            exit 1
          fi
        shell: bash

      - name: Upload Nuclear Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: nuclear-logs
          path: |
            gradle.log
            android/build/**/*
            ~/.gradle/
          retention-days: 7

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
