name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: '3.30.0'  # Matches your SDK constraint >=3.8.0

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-pub-cache-${{ env.FLUTTER_VERSION }}
          cache-path: /opt/hostedtoolcache/flutter

      - name: Validate Flutter version
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        working-directory: ./aurore_frontend
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        working-directory: ./aurore_frontend
        run: flutter test

      - name: Build release APK
        working-directory: ./aurore_frontend
        run: |
          flutter clean
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: aurore-app-release
          path: aurore_frontend/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      - name: Upload debug symbols
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-symbols
          path: aurore_frontend/build/symbols/
          retention-days: 30
