name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  WORKING_DIR: './aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter (Robust Method)
        run: |
          # Try multiple installation methods with fallbacks
          echo "Attempting Flutter installation..."
          
          # Method 1: Using home directory
          FLUTTER_HOME="$HOME/flutter_${{ env.FLUTTER_VERSION }}"
          mkdir -p "$FLUTTER_HOME"
          if [ ! -d "$FLUTTER_HOME/bin" ]; then
            echo "Downloading Flutter..."
            wget -q https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz || wget -q https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz
            echo "Extracting..."
            tar xf flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz -C "$FLUTTER_HOME" --strip-components=1 || exit 1
          fi
          
          echo "$FLUTTER_HOME/bin" >> $GITHUB_PATH
          echo "FLUTTER_HOME=$FLUTTER_HOME" >> $GITHUB_ENV

      - name: Verify Installation
        run: |
          echo "Verifying installation at $FLUTTER_HOME"
          ls -la "$FLUTTER_HOME/bin"
          flutter --version
          dart --version

      - name: Configure Environment
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Adjust SDK constraints to match Flutter 3.22.0 (Dart 3.4.0)
          sed -i \
            -e 's/sdk: ">=3.8.0 <4.0.0"/sdk: ">=3.4.0 <4.0.0"/' \
            -e 's/test: >=1.25.9/test: ^1.24.7/' \
            -e 's/firebase_auth: ^6.3.0/firebase_auth: ^4.11.0/' \
            pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter pub cache repair
          flutter pub get --verbose

      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter clean
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.WORKING_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
