name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.29.3'  # Matches your current environment
  WORKING_DIR: './aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Upgrade Gradle Project
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Backup current project
          mv android android_backup
          
          # Create new Flutter project
          flutter create -t app --project-name aurore_frontend --org com.example temp_project
          
          # Restore code and configuration
          mv temp_project/android .
          rm -rf temp_project
          cp -r android_backup/src/main/ android/app/src/main/
          cp android_backup/build.gradle android/
          cp android_backup/app/build.gradle android/app/
          cp android_backup/gradle.properties android/
          rm -rf android_backup

      - name: Prepare Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Update to compatible versions
          sed -i \
            -e 's/sdk: ">=.*\"/sdk: ">=3.7.0 <4.0.0"/' \
            -e 's/flutter: ">=.*\"/flutter: ">=3.29.0"/' \
            -e 's/material_color_utilities: .*/material_color_utilities: 0.11.1/' \
            -e 's/flutter_svg: .*/flutter_svg: ^2.1.0/' \
            -e 's/http: .*/http: ^1.1.0/' \
            -e 's/firebase_core: .*/firebase_core: ^2.24.0/' \
            -e 's/firebase_auth: .*/firebase_auth: ^4.11.0/' \
            -e 's/firebase_analytics: .*/firebase_analytics: ^10.4.0/' \
            pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter pub get
          flutter pub upgrade --major-versions

      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter clean
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.WORKING_DIR }}/build/app/outputs/flutter-apk/app-release.apk
