name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'  # Latest stable with Dart 3.4.0
  WORKING_DIR: './aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        run: |
          FLUTTER_HOME="${{ github.workspace }}/flutter"
          echo "FLUTTER_HOME=$FLUTTER_HOME" >> $GITHUB_ENV
          
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
          tar xf flutter_linux_${FLUTTER_VERSION}-stable.tar.xz -C "$FLUTTER_HOME" --strip-components=1
          echo "$FLUTTER_HOME/bin" >> $GITHUB_PATH

      - name: Adjust SDK Constraints
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Update both Dart and Flutter SDK constraints
          sed -i \
            -e 's/sdk: ">=3.8.0 <4.0.0"/sdk: ">=3.4.0 <4.0.0"/' \
            -e 's/flutter: ">=3.36.0"/flutter: ">=3.22.0"/' \
            pubspec.yaml

      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          flutter pub get
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.WORKING_DIR }}/build/app/outputs/flutter-apk/app-release.apk
