name: Flutter Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for Flutter projects

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-licenses: true
          android-sdk-platform: 34
          build-tools-version: 34.0.0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Validate Flutter Installation
        run: |
          flutter doctor -v
          flutter --version
        shell: bash

      - name: Recreate Android Files
        run: |
          if [ -d "android" ]; then
            rm -rf android
          fi
          flutter create --platforms android --project-name my_app .
          cd android && ./gradlew clean && cd ..
        shell: bash

      - name: Configure Gradle
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.java.home=$JAVA_HOME" > ~/.gradle/gradle.properties
          echo "android.jvmargs=-Xmx6144m" >> ~/.gradle/gradle.properties
          echo "org.gradle.jvmargs=-Xmx6144m -XX:+HeapDumpOnOutOfMemoryError" >> ~/.gradle/gradle.properties
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
          echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
        shell: bash

      - name: Setup Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > android/app/my-release-key.jks
          echo "storeFile=my-release-key.jks" > android/key.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
        shell: bash

      - name: Build Preparation
        run: |
          flutter pub get
          flutter clean
        shell: bash

      - name: Build APK (with retry)
        run: |
          set +e
          for i in 1 2 3; do
            echo "Attempt $i/3"
            flutter build apk --release --verbose > build.log 2>&1
            if [ $? -eq 0 ]; then
              cat build.log
              echo "Build succeeded on attempt $i"
              exit 0
            fi
            cat build.log
            echo "Build failed on attempt $i, retrying..."
            sleep 5
          done
          echo "All build attempts failed"
          exit 1
        shell: bash

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
