name: Flutter Build APK

on:
  push:
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Xmx6144m"
  _JAVA_OPTIONS: "-Xmx6144m -XX:MaxMetaspaceSize=2048m"
  ANDROID_SDK_ROOT: "/usr/local/lib/android/sdk"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-licenses: true
          android-sdk-platform: 34
          build-tools-version: '34.0.0'
          cmake-version: '3.22.1'
          ndk-version: '25.2.9519653'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Create Android Configuration
        run: |
          # Create Android directory if missing
          if [ ! -d "android" ]; then
            flutter create --platforms android --project-name app .
          fi
          
          # Create local.properties with SDK path
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          
          # Generate Gradle wrapper
          cd android && gradle wrapper --gradle-version 8.0.2 && cd ..
          
          # Make gradlew executable
          chmod +x android/gradlew
        shell: bash

      - name: Build APK
        run: |
          set -ex
          flutter clean
          flutter pub get
          
          cd android && ./gradlew clean assembleRelease \
            --stacktrace \
            --info \
            --no-daemon \
            --no-build-cache \
            --no-parallel \
            > ../gradle.log 2>&1 || (cat ../gradle.log && exit 1)
          
          if [ ! -f "../build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "APK generation failed!"
            ls -la ../build/app/outputs/flutter-apk/
            exit 1
          fi
        shell: bash

      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            gradle.log
            android/build/**/*.log
          retention-days: 7

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
