name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  WORKING_DIR: './aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: 'flutter-v3.22.0'

      - name: Verify Installation
        run: |
          flutter --version
          flutter doctor -v

      - name: Configure Firebase Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          # Update Firebase packages to versions compatible with Flutter 3.22.0
          sed -i \
            -e 's/firebase_core: ^[0-9.]*/firebase_core: ^2.24.0/' \
            -e 's/firebase_auth: ^[0-9.]*/firebase_auth: ^4.11.0/' \
            -e 's/firebase_messaging: ^[0-9.]*/firebase_messaging: ^14.7.0/' \
            -e 's/cloud_firestore: ^[0-9.]*/cloud_firestore: ^4.15.0/' \
            -e 's/sdk: ">=3.8.0 <4.0.0"/sdk: ">=3.4.0 <4.0.0"/' \
            pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "Running pub get..."
          flutter pub get
          
          echo "Checking for outdated packages..."
          flutter pub outdated --mode=null-safety

      - name: Build APK
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          set -e
          flutter clean
          flutter build apk --release \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.WORKING_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
