name: Flutter Build APK

on:
  push:
    branches: [main]

env:
  FLUTTER_VERSION: '3.24.3'
  JAVA_VERSION: '17'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Check for invalid references
        run: |
          echo "Checking for school_management2 or aurore_app references..."
          grep -r "school_management2\|aurore_app" . || echo "No invalid references found"

      - name: Verify project structure
        run: |
          echo "Checking critical files..."
          ls -la pubspec.yaml lib/main.dart test/widget_test.dart || exit 1
          echo "Checking assets..."
          ls -la assets/images/ assets/icons/ || echo "Assets not found, continuing..."
          echo "Checking fonts..."
          ls -la fonts/ || echo "Fonts not found, continuing..."
          echo "Checking lib structure..."
          find lib/ -type f || exit 1

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub upgrade
          flutter analyze > flutter_analyze.log 2>&1 || (cat flutter_analyze.log && exit 1)
          flutter pub deps > flutter_deps.log 2>&1 || (cat flutter_deps.log && exit 1)

      - name: Build APK
        run: |
          flutter clean
          flutter build apk --release --verbose > flutter_build.log 2>&1 || (cat flutter_build.log && exit 1)

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            flutter_analyze.log
            flutter_deps.log
            flutter_build.log
            gradle.log
            android/build/**/*
            build/
          retention-days: 7

      - name: Upload APK on success
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
