name: Build APK and IPA

on:
  push:
    branches:
      - update-gradle
  pull_request:
    branches:
      - update-gradle

jobs:
  fetch-flutter-version:
    runs-on: ubuntu-latest
    outputs:
      flutter_version: ${{ steps.set-flutter-version.outputs.flutter_version }}
    steps:
      - name: Set Flutter version
        id: set-flutter-version
        run: |
          echo "Using Flutter version 3.29.3 (matches pubspec.yaml and logs)"
          echo "flutter_version=3.29.3" >> $GITHUB_OUTPUT

  build-android:
    needs: fetch-flutter-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: aurore-FRONTEND

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-level: '36'
          ndk-version: '27.0.12077973'

      - name: Install Android SDK command-line tools
        run: |
          echo "Installing Android SDK command-line tools"
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-12269904_latest.zip
          unzip -o cmdline-tools.zip -d "$ANDROID_HOME/cmdline-tools"
          mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"
          rm cmdline-tools.zip
          echo "Verifying sdkmanager"
          sdkmanager="$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"
          if [ -x "$sdkmanager" ]; then
            echo "sdkmanager found at $sdkmanager"
            $sdkmanager --version
          else
            echo "Error: sdkmanager not found at $sdkmanager"
            exit 1
          fi
          echo "Adding sdkmanager to PATH"
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

      - name: Accept Android licenses
        run: |
          echo "Accepting Android licenses"
          sdkmanager="$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager"
          yes | $sdkmanager --licenses --sdk_root=$ANDROID_HOME || echo "sdkmanager --licenses failed, trying flutter doctor"
          flutter doctor --android-licenses --accept || { echo "Error: Failed to accept licenses"; exit 1; }
          echo "Verifying licenses"
          if ls "$ANDROID_HOME/licenses" | grep -q "android-sdk"; then
            echo "Licenses accepted successfully"
            ls -la "$ANDROID_HOME/licenses"
          else
            echo "Error: License files not found in $ANDROID_HOME/licenses"
            exit 1
          fi
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.fetch-flutter-version.outputs.flutter_version }}
          channel: 'stable'
          architecture: 'x64'

      - name: Verify Flutter setup
        run: |
          echo "Running flutter doctor"
          flutter doctor -v > flutter_doctor.log
          cat flutter_doctor.log
          if grep -q "Some Android licenses not accepted" flutter_doctor.log; then
            echo "Error: Android licenses still not accepted"
            exit 1
          fi
          flutter --version || { echo "Error: Flutter not found"; exit 1; }
          dart --version || { echo "Error: Dart not found"; exit 1; }
          dart_version=$(dart --version 2>&1 | grep -o '[0-9]+\.[0-9]+\.[0-9]+')
          echo "Dart version: $dart_version"

      - name: Verify directory
        run: |
          echo "Verifying directory structure"
          pwd
          ls -la .
          if [ -d "./aurore-FRONTEND" ]; then
            echo "Found aurore-FRONTEND directory"
            cd ./aurore-FRONTEND
            ls -la .
            if [ -d "./aurore_frontend" ]; then
              echo "Found aurore_frontend directory"
              cd ./aurore_frontend
              ls -la .
              if [ -f "pubspec.yaml" ]; then
                echo "Found pubspec.yaml in aurore_frontend"
                cat pubspec.yaml
              else
                echo "Error: pubspec.yaml not found in aurore_frontend"
                ls -la .
                exit 1
              fi
            else
              echo "Error: aurore_frontend directory not found"
              ls -la .
              exit 1
            fi
          else
            echo "Error: aurore-FRONTEND directory not found"
            ls -la .
            exit 1
          fi

      - name: Install dependencies
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          echo "Installing Flutter dependencies"
          flutter pub get || { echo "Error: Failed to get dependencies"; echo "pubspec.yaml content:"; cat pubspec.yaml; flutter pub get --verbose; exit 1; }

      - name: Set up Android signing
        working-directory: ./aurore-FRONTEND/aurore_frontend
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo "Setting up Android signing"
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/keystore.jks
          cat > android/key.properties <<EOF
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyPassword=$ANDROID_KEY_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          storeFile=keystore.jks
          EOF
          echo "Android signing setup complete"

      - name: Update build.gradle.kts for release signing
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          echo "Updating android/app/build.gradle.kts"
          cat > android/app/build.gradle.kts <<EOF
          plugins {
              id("com.android.application")
              id("org.jetbrains.kotlin.android")
              id("com.google.gms.google-services")
          }

          android {
              namespace = "com.example.aurore_frontend"
              compileSdk = flutter.compileSdkVersion
              ndkVersion = "27.0.12077973"

              compileOptions {
                  sourceCompatibility = JavaVersion.VERSION_11
                  targetCompatibility = JavaVersion.VERSION_11
              }

              kotlinOptions {
                  jvmTarget = JavaVersion.VERSION_11.toString()
              }

              defaultConfig {
                  applicationId = "com.example.aurore_frontend"
                  minSdk = flutter.minSdkVersion
                  targetSdk = flutter.targetSdkVersion
                  versionCode = flutter.versionCode
                  versionName = flutter.versionName
              }

              signingConfigs {
                  register("release") {
                      keyAlias = System.getenv("ANDROID_KEY_ALIAS")
                      keyPassword = System.getenv("ANDROID_KEY_PASSWORD")
                      storeFile = file("keystore.jks")
                      storePassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
                  }
              }

              buildTypes {
                  release {
                      signingConfig = signingConfigs.getByName("release")
                  }
              }
          }

          flutter {
              source = "../.."
          }
          EOF
          echo "Updated android/app/build.gradle.kts with release signing"
          cat android/app/build.gradle.kts

      - name: Build APK
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          echo "Building APK"
          flutter build apk --release || { echo "Error: APK build failed"; cat android/app/build.gradle.kts; flutter build apk --release --verbose; exit 1; }
          echo "APK built at build/app/outputs/flutter-apk/app-release.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: aurore-FRONTEND/aurore_frontend/build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    needs: fetch-flutter-version
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: aurore-FRONTEND

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.fetch-flutter-version.outputs.flutter_version }}
          channel: 'stable'
          architecture: 'x64'

      - name: Verify Flutter setup
        run: |
          echo "Running flutter doctor for iOS"
          flutter doctor -v > flutter_doctor.log
          cat flutter_doctor.log
          if ! grep -q "Xcode - develop for iOS and macOS" flutter_doctor.log; then
            echo "Error: Xcode not properly configured"
            exit 1
          fi
          if ! grep -q "CocoaPods" flutter_doctor.log; then
            echo "Error: CocoaPods not properly configured"
            exit 1
          fi
          if grep -q "Some Android licenses not accepted" flutter_doctor.log; then
            echo "Warning: Android licenses not accepted (ignoring for iOS build)"
          fi
          flutter --version || { echo "Error: Flutter not found"; exit 1; }
          dart --version || { echo "Error: Dart not found"; exit 1; }
          dart_version=$(dart --version 2>&1 | grep -o '[0-9]+\.[0-9]+\.[0-9]+')
          echo "Dart version: $dart_version"

      - name: Verify directory
        run: |
          echo "Verifying directory structure"
          pwd
          ls -la .
          if [ -d "./aurore-FRONTEND" ]; then
            echo "Found aurore-FRONTEND directory"
            cd ./aurore-FRONTEND
            ls -la .
            if [ -d "./aurore_frontend" ]; then
              echo "Found aurore_frontend directory"
              cd ./aurore_frontend
              ls -la .
              if [ -f "pubspec.yaml" ]; then
                echo "Found pubspec.yaml in aurore_frontend"
                cat pubspec.yaml
              else
                echo "Error: pubspec.yaml not found in aurore_frontend"
                ls -la .
                exit 1
              fi
            else
              echo "Error: aurore_frontend directory not found"
              ls -la .
              exit 1
            fi
          else
            echo "Error: aurore-FRONTEND directory not found"
            ls -la .
            exit 1
          fi

      - name: Install dependencies
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          echo "Installing Flutter dependencies"
          flutter pub get || { echo "Error: Failed to get dependencies"; echo "pubspec.yaml content:"; cat pubspec.yaml; flutter pub get --verbose; exit 1; }

      - name: Set up Ruby and CocoaPods
        run: |
          echo "Installing CocoaPods"
          gem install cocoapods
          pod --version

      - name: Install CocoaPods dependencies
        working-directory: ./aurore-FRONTEND/aurore_frontend/ios
        run: |
          echo "Running pod install"
          pod install || { echo "Error: Failed to install CocoaPods dependencies"; pod install --verbose; exit 1; }
          echo "CocoaPods dependencies installed"

      - name: Set up code signing
        working-directory: ./aurore-FRONTEND/aurore_frontend
        env:
          IOS_CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          IOS_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo "Setting up iOS code signing"
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          echo "$IOS_CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$IOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$IOS_PROVISIONING_PROFILE_BASE64" | base64 --decode > profile.mobileprovision
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          sed -i '' 's/Automatic/Manual/' ios/Runner.xcodeproj/project.pbxproj
          echo "Code signing setup complete"

      - name: Build IPA
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          echo "Building iOS app"
          flutter build ios --release --no-codesign || { echo "Error: iOS build failed"; flutter build ios --release --no-codesign --verbose; exit 1; }
          cd ios
          echo "Archiving with xcodebuild"
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath build/Runner.xcarchive || { echo "Error: xcodebuild archive failed"; xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath build/Runner.xcarchive -verbose; exit 1; }
          echo "Exporting IPA"
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist ../exportOptions.plist -exportPath build/ipa || { echo "Error: xcodebuild export failed"; xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist ../exportOptions.plist -exportPath build/ipa -verbose; exit 1; }
          echo "IPA built at build/ipa/Runner.ipa"

      - name: Create exportOptions.plist
        working-directory: ./aurore-FRONTEND/aurore_frontend
        run: |
          echo "Creating exportOptions.plist"
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>teamID</key>
            <string>${{ secrets.APPLE_TEAM_ID }}</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
          </dict>
          </plist>
          EOF
          echo "Created exportOptions.plist"
          cat exportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Runner.ipa
          path: aurore-FRONTEND/aurore_frontend/ios/build/ipa/Runner.ipa
