name: Build APK

on:
  push:
    branches:
      - update-gradle
  pull_request:
    branches:
      - update-gradle

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (required for Android builds)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0' # Specify a stable Flutter version
          channel: 'stable'

      # Get Flutter dependencies
      - name: Install dependencies
        working-directory: ./auroe_frontend
        run: flutter pub get

      # Build the APK
      - name: Build APK
        working-directory: ./auroe_frontend
        run: flutter build apk --release

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4 # Updated to v4 for better compatibility
        with:
          name: app-release.apk
          path: auroe_frontend/build/app/outputs/flutter-apk/app-release.apk
