name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Generate local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > android/local.properties
          echo "flutter.sdk=$FLUTTER_HOME" >> android/local.properties
          echo "flutter.versionCode=1" >> android/local.properties
          echo "flutter.versionName=1.0.0" >> android/local.properties

      - name: Clean workspace
        run: |
          flutter clean
          rm -rf ~/.gradle/caches
          rm -rf android/.gradle

      - name: Resolve dependencies
        run: flutter pub get

      - name: Build APK (with debug logs)
        run: |
          flutter build apk --release --verbose 2>&1 | tee build.log
          if [ $? -ne 0 ]; then
            echo "::error::Build failed. Check build.log for details"
            cat build.log
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
          if-no-files-found: error
