name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  PROJECT_DIR: 'aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Project Structure
        run: |
          [ -f "${{ env.PROJECT_DIR }}/pubspec.yaml" ] || {
            echo "::error::pubspec.yaml not found in ${{ env.PROJECT_DIR }}!"
            exit 1
          }

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Modify Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Correct yq command with YAML format specification
          yq eval -i -y '
            del(.dependencies.test) |
            del(.dev_dependencies.test) |
            .dev_dependencies.flutter_test.sdk = "flutter" |
            .dependencies.firebase_core = "2.24.0" |
            .dependencies.firebase_auth = "4.11.0" |
            .environment.sdk = ">=3.4.0 <4.0.0" |
            .environment.flutter = ">=3.22.0 <4.0.0"
          ' pubspec.yaml

          echo "Modified pubspec.yaml:"
          cat pubspec.yaml

      - name: Resolve Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub get

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter clean
          flutter build apk --release \
            --no-sound-null-safety \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
