name: Aurore Frontend CI/CD

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.0'
  PROJECT_DIR: 'aurore_frontend'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Increased timeout for Gradle operations

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: 'flutter-${{ env.FLUTTER_VERSION }}'

      - name: Verify Installation
        run: |
          flutter --version
          flutter doctor -v

      - name: Fix Gradle Project Structure
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Create temporary new project
          TEMP_DIR=$(mktemp -d)
          flutter create -t app $TEMP_DIR/new_project
          
          # Migrate essential files
          cp -r lib $TEMP_DIR/new_project/
          cp -r assets $TEMP_DIR/new_project/
          cp -r test $TEMP_DIR/new_project/
          cp pubspec.yaml $TEMP_DIR/new_project/
          
          # Replace old project with fixed structure
          rm -rf *
          cp -r $TEMP_DIR/new_project/* .
          rm -rf $TEMP_DIR

      - name: Update Dependency Versions
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          # Install yq for YAML processing
          sudo snap install yq

          # Update dependencies to exact compatible versions
          yq eval '.dependencies.test = "1.24.0"' -i pubspec.yaml
          yq eval '.dependencies.typed_data = "1.3.2"' -i pubspec.yaml
          yq eval '.dependencies.vector_math = "2.1.4"' -i pubspec.yaml
          yq eval '.dependencies.vm_service = "14.2.1"' -i pubspec.yaml
          yq eval '.dependencies.web_socket_channel = "2.4.0"' -i pubspec.yaml
          
          # Set SDK constraints
          yq eval '.environment.sdk = ">=3.4.0 <4.0.0"' -i pubspec.yaml
          yq eval '.environment.flutter = ">=3.22.0 <4.0.0"' -i pubspec.yaml

          # Verify YAML
          if ! python3 -c "import yaml; yaml.safe_load(open('pubspec.yaml'))"; then
            echo "::error::Invalid YAML after modification!"
            exit 1
          fi

      - name: Resolve Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get --no-upgrade
          flutter pub outdated --mode=null-safety

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -e
          flutter clean
          flutter build apk --release \
            --no-sound-null-safety \
            --dart-define=CI_ENV=true \
            --split-debug-info=build/symbols/ \
            --obfuscate

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
