name: Flutter APK Builder (Dart 3.8.6 - Final Solution)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: '3.16.9'
  FLUTTER_HOME: '/opt/flutter'
  DART_VERSION: '3.8.6'
  DART_SDK_PATH: './tools/dart-sdk/dart-sdk-linux-x64.zip'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This is CRUCIAL to get the SDK

      - name: Verify Dart SDK
        run: |
          # Check file exists and is valid
          if [ ! -f "${{ env.DART_SDK_PATH }}" ]; then
            echo "::error::MISSING DART SDK - YOU MUST FOLLOW THESE STEPS:"
            echo "1. Run these commands in your local repository:"
            echo "   mkdir -p tools/dart-sdk"
            echo "   wget https://storage.googleapis.com/flutter_infra_release/flutter/2e2c8d9cf472ce9b0c4d2b9dd5f1b1c5a9e8a7a1/dart-sdk-linux-x64.zip -O tools/dart-sdk/dart-sdk-linux-x64.zip"
            echo "   git add tools/dart-sdk/dart-sdk-linux-x64.zip"
            echo "   git commit -m 'Add Dart SDK'"
            echo "   git push"
            echo "2. Verify the file exists locally before pushing"
            exit 1
          fi
          
          echo "Dart SDK found - proceeding with build"

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git unzip

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b ${{ env.FLUTTER_VERSION }} --depth 1 ${{ env.FLUTTER_HOME }}
          echo "${{ env.FLUTTER_HOME }}/bin" >> $GITHUB_PATH

      - name: Install Dart SDK
        run: |
          echo "=== Installing Dart SDK ==="
          rm -rf ${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk
          unzip -q ${{ env.DART_SDK_PATH }} -d ${{ env.FLUTTER_HOME }}/bin/cache/
          
          # Verify version
          DART_ACTUAL=$(${{ env.FLUTTER_HOME }}/bin/cache/dart-sdk/bin/dart --version 2>&1 | awk '{print $4}')
          echo "Installed Dart version: $DART_ACTUAL"
          
          if [ "$DART_ACTUAL" != "${{ env.DART_VERSION }}" ]; then
            echo "::error::Wrong Dart version installed!"
            exit 1
          fi

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter pub get
          flutter build apk --release --shrink

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
