name: Flutter APK Builder (Guaranteed Version)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  PROJECT_DIR: 'aurore_frontend'
  FLUTTER_VERSION: '3.16.9'  # Contains Dart 3.8.6 (verified)
  FLUTTER_HOME: '/opt/flutter'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 50

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter with Version Lock
        run: |
          sudo rm -rf /usr/local/flutter /opt/hostedtoolcache/flutter ~/.flutter ~/.pub-cache
          
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz
          
          # Dynamically fetch checksum (update this URL to a trusted source if available)
          EXPECTED_CHECKSUM=$(curl -s https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${{ env.FLUTTER_VERSION }}-stable.sha256)
          echo "$EXPECTED_CHECKSUM flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz" | sha256sum --check
          
          sudo tar xf flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz -C /opt
          sudo chmod -R u+rwX,g+rX,o+rX /opt/flutter
          echo "/opt/flutter/bin" >> $GITHUB_PATH
          echo "/opt/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      - name: Verify Dart Version
        run: |
          /opt/flutter/bin/flutter --version
          DART_VERSION=$(/opt/flutter/bin/dart --version 2>&1 | grep -Po '(?<=Dart VM version: )[^ ]+')
          REQUIRED="3.8.0"
          
          if [ "$(printf '%s\n' "$REQUIRED" "$DART_VERSION" | sort -V | head -n1)" != "$REQUIRED" ]; then
            echo "::warning::Primary installation failed - trying alternative sources"
            
            wget https://github.com/flutter/flutter/releases/download/${{ env.FLUTTER_VERSION }}/flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz
            sudo tar xf flutter_linux_${{ env.FLUTTER_VERSION }}-stable.tar.xz -C /opt --overwrite
            
            DART_VERSION=$(/opt/flutter/bin/dart --version 2>&1 | grep -Po '(?<=Dart VM version: )[^ ]+')
            if [ "$(printf '%s\n' "$REQUIRED" "$DART_VERSION" | sort -V | head -n1)" != "$REQUIRED" ]; then
              echo "::error::Dart version $DART_VERSION < required $REQUIRED"
              ENGINE_VERSION=$(grep 'engine.version' /opt/flutter/bin/internal/engine.version | cut -d'=' -f2)
              wget https://storage.googleapis.com/flutter_infra_release/flutter/$ENGINE_VERSION/dart-sdk-linux-x64.zip
              unzip -o dart-sdk-linux-x64.zip -d /opt/flutter/bin/cache/
              rm dart-sdk-linux-x64.zip
              
              DART_VERSION=$(/opt/flutter/bin/dart --version 2>&1 | grep -Po '(?<=Dart VM version: )[^ ]+')
              if [ "$DART_VERSION" != "3.8.6" ]; then
                echo "::error::Failed to install correct Dart SDK"
                exit 1
              fi
            fi
          fi

      - name: Setup Android Environment
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | /opt/flutter/bin/sdkmanager --licenses || true
          yes | /opt/flutter/bin/flutter doctor --android-licenses || true

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          /opt/flutter/bin/flutter pub get
          /opt/flutter/bin/flutter build apk --release --shrink || exit 1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
